#+title: Arkham Horror LCG Rules
#+author: BoingoBoiActual

* Learn to Play
** First Game Setup
   To set up the first game, perform the following steps in order. The game is best learned with one or two players.
   1. *Choose Investigator(s)*. Each player chooses an investigator and places that investigator's card in his or her play area. For the first game, it is recommended that one player use Roland Banks. If there is a second player, it is recommended that that player use Wendy Adams.
   2. *Choose one of those investigators to be the lead investigator for this game, and give that player the Campaign Guide.*
      - /The lead investigator is the player who will break ties and make decisions for the group whenever there is a conflict./
   3. *Assemble and shuffle the player decks*. The cards used in each of the recommended investigators' starter decks are detailed in the "Investigaror Starter Decks" entry.
      - /Some cards have an upgraded version with one or more white pips in the upper left-hand cornder of the card. When building these starter decks, *do not* include these upgraded version./
   4. *Assemble the token pool.* Place the damage, horror, clue/doom, and resource tokens within easy reach of all investigators.
      - /The token pool serves as a repository for all tokens that are not being used at a given moment/
   5. *Assemble the chaos bag.* Place the 16 chaos tokens indicated below into an opaque container such as a bag, bowl, or cup. This container is referred to as the "chaos bag." Return the other chaos tokens to the game box. +1, 0, 0, -1, -1, -1, -2, -2, -3, -4, S, S, C, T, F, E
      - /Throughout the game, the investigators are asked to randomly reveal tokens from the chaos bag to modify their chances of success or failure in a variety of situations./
   6. *Take starting resources.* Each investigator takes 5 resources from the token pool and places them near his or her investigator card. This is the investigator's resource pool.
      - /Resources are spend by an investigator to play cards from his or her hand./
   7. *Draw opening hands.* Each investigator draws 5 cards from his or her deck. If a weakness card is drawn at any point during this step, set it aside instead of adding it to your hand, draw an additional  card, and then shuffle the weakness back into your deck.
      - /Each player may take a single mulligan at this time, if desired, by setting aside up to 5 of the cards just drawn, drawing an equivalent number of cards, and shuffling the set-aside cards back into his or her deck. Taking a mulligan is recommended if a player does not recieve a decent starting hand. For instance, drawing no assets would be a good reason to take a mulligan./
** Scenario Setup (First Game Setup Continued)
    The following steps refer to scenario-specific information for the first scenario in the /Night of the Zealot/ campaign.
   8. *Read the scenario introduction for "The Gathering."* The introduction for this scenario is the italicized flavor text in the beginning of /Night of the Zealot/ Campaign Guide, under "Part 1: The Gathering."
      - /The scenario introduction provides a narrative hook for the tale that is about to unfold. Pay attention to such narrative passages, both in the Campaign Guide and itn card flavor text, as important details may be revealed that inform or add contet for decisions made later in the scenario./
   9. *Find the scenario cards for "The Gathering"* The encounter sets used in this scenario are: /The Gathering/, /Rats/, /Ghouls/, /Striking Fear/, /Ancient Evils/, and /Chilling Cold/. The cards in each encounter set have a symbol identifying them as part of that encounter set. In the Campaign Guide, this information is presented in the following manner: 
      - Gather all cards from the following encounter sets: /The Gathering/, /Rats/, /Ghouls/, /Striking Fear/, /Ancient Evils/, and /Chilling Cold/. The book also includes icons for identification.
      - /When gathering encounter cards, gather all copies of each card in the listed encounter set. Use the encounter set numbers at the bottom of each encounter card to aid you./
   10. *Set agenda deck.* Assemble the agenda deck (in sequential order so that "agenda 1a" is on top, "agenda 2a" is next, etc.) using the agenda cards from the encounter sets found curing step 9. Read the story text on agenda 1a.
      - /The agenda deck represents the progress made by the dark forces of the Mythos. Generally, the investigators do *not* want the agenda deck to advance./
   11. *Set act deck.* Assemble the act deck (in sequential order so that "act 1a" is on top, "act 2a" is next, etc.) using the act cards from the encounter sets found during step 9. Read the story text on act 1a.
      - /The act deck represents porgress made by the investigators toward solving the mystery or achieving their objectives in a scenario. Generally, the investigators *want* the act deck to advance./
   12. *Place the scenario reference card for "The Gathering" next to the agenda deck.* Use the "easy/standard" side for this tutorial.
      - /This card is referenced each time a S, C, or T token is selected from the chaos bag to indicate how that token affects the game state./
   13. *Put the Study into play.* When a location is put into play, it always enters play with its *unrevealed* side faceup. The unrevealed side of a location can be identified by the presence of a keyhole symbol below its title.
      - /Read the flavor text on the unrevealed side fo the Study at this time./
   14. *Set every other location aside, out of play.* These cards are the Hallway, Attic, Cellar, and Parlor.
      - /When the players are instructed to "set aside" encounter or player cards, those cards are not used right away but should be kept close at hand, as they may be needed at a later point during a scenario./
   15. *Each investigator begins play in the Study.* Place each investigator's mini card next to the Study to represent that each investigator is in the Study.
      - /When an investigator enters (or begins play at) a location, flip that location to its *Revealed* side. The revealed side of a location can be identified by the presence of shroud and clue values. When a location is revealed, place clues on it equal to its clue value, which, for the Study, is 2 clues per investigator. The shroud value is located on the left center, the clue value is located on the right center./
   16. *Set the Ghoul Priest and Lita Chantler cards aside, out of play.*
   17. *Assemble the encounter deck.* Take the remainder of the cards found during step 9, and shuffle them together to create the encounter deck. 
      - /Throughout the game, investigators will draw encounter cards from this deck representing perils, monsters, madnesses, and other afflictions they must overcome in order to succeed./
      A diagram of a suggested play area is presented on the following page.
   18. *The game is ready to begin.*

** Key Concepts
   This section introduces a number of foundational concepts important to learning and playing the game.
*** The Golden Rule
    If the text on a card directly contradicts the text of the rules, the text on the card takes precedence. If it is possible to observe both the card text and the text of the rules, both are observed.
*** Choices and Conflicts
    If the players are required to make a choice among two or more equally valid options, the lead investigator chooses among those options.
    If the players are unsure how to resolve a rule or timing conflict, resolve the conflict in the manner the players percieve as the worst possible at the moment with regards to winning the scenario, and continue with the game. This is known as "The Grim Rule" and using this rule helps to keep the game moving without forcing the players to look up every conflict they discover.
*** Winning and Losing
    As the players advance through a scenario, they will eventually reach a resolution. Some of these resolutions are favorable; others are less favorable and leave the investigators in a more dire situation.
    The act deck represents the progress of the investigators through a scenario. The players' primary objective is to gather clues and use them to advance through the act deck until a resolution is reached.
    The agenda deck represents the objectives and progress of the malicious forces pitted against the investigators in the scenario. Should the agenda deck reach its conclusion, a resolution will occur.
    When any encounter card triggers a resolution - denoted by the text "(->R#)" - the players have completed the scenario and should refer to the resolution text that matches that number in the Campaign Guide to discover what happens next.
    Should all investigators be eliminated during a scenario, the "if no resolution was reached" conclusion in the Campaign Guide is used.
*** "In Player Order"
    The phrase "in player order" is used to dictate the order in which players resolve or execute a game step. When players are instructed to do something "in player order", the lead investigator does so first, followed by each other player, one player at a time, in clockwise order around the table.
*** Per Investigator
    The Inv symbol next to a value multiplies that value by the number of investigators who started the scenario. The number of clues that are placed on a location and the number of clues necessary to advance the current act are often denoted with this symbol.
*** Ready and Exhausted
    Cards enter play in a ready position (upright, so that the ability text can be read from left to right). In ordre to use some card abilities, the card must exhaust, which is indicated by rotating the card 90 degrees. A card in the exhausted position is not able to exhaust again until it is ready (either by game step or card ability).
*** Locations
    Locations represent the various places the investigators travel to during a scenario while looking for clues. Each locaiton has two sides: a revealed side and an unrevealed side. The revealed side of a locaiton has a shroud value and a clue value. The unrevealed side does not show this information, and it has a keyhole symbol below its title.
    A location enters play unrevealed side faceup. When an investigator enters a location for the first time, it is revealed, and a number of clues equal to that location's clue value are places on that locaiton. This may occur during setup if the investigators begin play at a location, or if the setup rules instruct the players to reveal a location.
*** Skills and Skill Tests
    Each investigator possesses four skills: Willpower, Intellect, Combat, and Agility. The higher an investigator's value for a particular skill, the better that investigator is at performing tasks with that skill.
    A number of situations require an investigator to make a *skill test*. A skill test pits the investigator's value in a specified skill agains a difficulty value determined by the ability or game step that initiated the test. To perform a skill test, a player reveals a random chaos token from the chaos bag, which modifies his or her skill value. If the modified skill value equals or exceeds the test's difficulty, the investigator succeeds at the test. The consequences of succeeding at or failing a test are provided by the card or aciton that initiated the test.
**** Modifying Skill Value for Skill Tests
    Before drawing a chaos token for a skill test, the investigator /may/ boost his or her skill balue. There are two ways to do this:
    First, the investigator may commit eligible cards from his or her hand to the test. An eligible card bears one or more icons matching the skill type of the test being performed. A wild icon "?" matches all skill types. Each matching icon commited to a test increases the investigator's skill value by 1 for that test. The investigator performing the test may commit any number of cards from his or her hand to the test. Each /other/ investigator at the same location as that investigator may commit 1 card from his or her hand to help.
    Do not pay a card's resource cost when committing it to a skill test.
    In addition, the investigator may activate FT (Free Trigger) abilities to modify his or her skill for a test.
**** Chaos Token Effects
    Each chaos token has a symbol or numerical modifier that influences the outcome of a skill test. The effect of each chaos token is described as follows.
    S(Skull), C(Cultist), T(Tablet), O(Old One) - Refer to the scenario reference card and resolve the corresponding effect.
    E(Elder Sign) - Refer to your investigator card and resolve your investigator's E ability.
    F(Failure) - Indicates an automatic failure of the skill test.
    If the revealed chaos token (or the effect referenced by a chaos token) has a numerical modifier, that modifier is applied to the investigator's skill value for this test.
**** Concluding a Skill Test
    If the investigator's modified skill value is equal to or higher than the difficulty value of the skill test, the investigator succeeds at the test. Otherwise, the investigator fails. The ability or game step taht initiated the skill test provides instructions for the consequences of succeeding and/or failing. 
    Some skill cards have an ability that resolves upon the completion of a skill test, if the card is committed to that test.
    Upon completion of a skill test, discard all investigator cards committed to that test, and return the revealed chaos token to the chaos bag.
*** Weakness Cards
    A weakness card is a card in an investigator's deck that has an ill effect when drawn. These cards are identified by the label "Weakness" or "Basic Weakness" beneath the card's title or artwork. When one of these cards is drawn, the investigator who drew the card must resolve its "*Revelation*" ability immediately.
** Round Sequence
   /Arkham Horror: LCG/ is played over a series of rounds. During a round, the investigators encounter the terrifying forces of the Mythos, move through and explore mysterious locations, fend off dangerous enemies, and finally, collect their bearings in anticipation of the next round.
   Each round is divided into the following four phases:
   1. Mythos phase
   2. Investigation phase
   3. Enemy phase
   4. Upkeep phase
   *Important Note:* During the first round of each game, skip the mythos phase. Proceed to the investigation phase. The mythos phase is described later.
   Once all four phases are complete, the round is over, and play proceeds to the mythos phase of the next round. Each phase is described in detail below.
*** The Investigation Phase
    During this phase, each investigator takes a separate turn. The investigators, as a group, choose which investigator takes the first turn. When an investigator's turn ends, choose an investigator to take the next turn, and so on, until each investigator has taken his or her turn.
    Each investigator has three actions during his or her turn that may be used to perform a variety of tasks. An investigator may perform any of the following, as mny times as he or she would like, and in any order, providing the investigator has an action available to pay for that task. On his or her turn, an investigator may use an action to:
    - *Draw* 1 card.
    - Gain 1 *Resource*.
    - *Activate* an AT (action trigger) ability.
    - *Engage* an enemy at his or her current location.
    - *Investigate* his or her current location.
    - *Move* to a new connecting location.
    - *Play* an asset or even card from his or her hand.
    - Attempt to *Evade* an enemy engaged with him or her.
    - *Fight* an enemy at his or her current location.
    If an investigator is engaged with one or more ready enemies, performing any action other than to *Evade*, to *Fight*, or to Activate an ability with either a *Parley* or *Resign* designator in its text causes each of those enemies to attack the investigator. This type of attack is called an *Attack of Opportunity*. 
    An investigator may end his or her turn early if there are no other actions he or she wishes to perform. To indicate that an invetigator's turn is over, flip his or her mini card facedown, to its black and white side. Unused actions are lost and cannot be saved for future turns. After each investigator has completed his or her turn, play proceeds to the enemy phase.
    Each of the actions is described in detail in the following sections:
**** Draw
     The investigator using this action draws one card from the top of their deck.
**** Resource
     The investigator using this action gains one resource from the token pool.
**** Activate
     The investigator using this action resolves an TA (Triggered Action) ability on a card under his or her control, on an encounter card at his or her location, or on the current act or agenda card.
**** Engage
     The investigator using this action engages one enemy that is at his or her location. To engage an enemy, the investigator places that enemy in his or her threat area. 
**** Investigate
     The investigator using this action investigates his or her current location in an attempt to find clues. That investigator makes an Intellect test against the shroud value of that location:
     If the skill test is successful, the investigator has succeeded and discovers one clue from the location. When an investigator disovers a clue from a location, that player takes one clue that was on the location and places it on his or her investigator card.
     If the test is failed, no clues are discovered.
***** Advancing the Act Deck
      The act deck represents progress the investigators can make in a scenario. Generally, the investigators can advance the act deck by spending, as a group, an appropriate number of clues. Spend clues are returned from the investigators cards to the general token pool. Advancing the act in this way does not cost an action and may be done during any investigator's turn. The number of clues required to advance to the next act can be found at the bottom of the current act card's text box.
      If the current act has a boldface "*Objective*" instruction, that instruction overrides the procedure for advancing the act deck described above. 
      To advance the act deck, flip the current act over to its "b" side, follow the instructions on the back, and set it aside, out of play. The next card in the act deck becomes the new current act. When advancing the act deck, any clues te investigators have gained (but are not spending) remain in their play area.
**** Move
     The investigator using this action moves to a connecting location. Move that investigator's mini card to any other location that is marked as a connection on the investigator's current location. A location's connections are indicated by the icons at the bottom of the location card, which each match and identical icon in the title area of each connecting location.
     If the connecting location is unrevealed, the location is turned to its revealed side when an investigator moves to it. Remember to place the indicated number of clues on the location when this occurs.
**** Play
     When an investigator uses this action, that investigator selects an asset or event card in his or her hand, pays its resource cost, and plays it. A card's resource cost and cardtype are found in its upper left corner.
     To pay a resource cost, the investigator playing the card must move a number of resources equal to the cost from his or her resource pool to the general token pool.
     The rules for playing each cardtype are as follows:
     - If the played card is an *event card*, its effects are resolved and it is then placed in its owner's discard pile.
     - If the played card is an *asset card*, it is placed in the play area of the investigator playing the card and remains in play until an ability or game effect causes it to leave play.
     - *Skill cards are not played.* For their abilities and icons to be used, these cards must be committed to a skill test from a player's hand.
     Cards with the fast keyword do not cost and action to play.
***** Slots
      Slots restrict the number of cards of a specific category an investigator can have in play at one time. If an asset has one or more slot symbols, it may only enter play if its controller has those slots available.
      The slots avialable to an investigator are: 
      - 1 ally slot, 1 body slot, 1 accessory slot, 2 hand slots, and 2 arcane slots
      If an investigator wishes to play or gain control of an asset that requires a slot already held by a different asset, the investigator must choose and discard and asset or assets under his or her control to make room for the newly aquired asset.
**** Evade
     The investigator using this action attempts to evade one enemy he or she is engaged with. The investigator makes an Agility test against that enemy's evad value:
     If the skill test is successful, the investigator successfully evades the enemy. The enemy is exhausted, and the engagement is broken. Move the enemy from the investigator's threat area to the investigator's current location to mark that it is no longer engaged dwith that investigator.
     If the Agility test fails, the enemy is not evaded and remains engaged with the investigator.
**** Fight
     The investigator using this action attacks one enemy that is at his or her location. That investigator makes a Combat test against the enemy's fight value:
     If the combat test is successful, the attack succeeds and the investigator *deals 1 damage* to the attacked enemy. Some weapons, spells, or other special attacks may modify the amount of damage dealt. Place a number of damage tokens equal to the amount of damage dealt on the enemy. If an enemy has as much damage on it as it has health, the enemy is defeated and placed in the encounter discard pile. If the bottom of the enemy's text box indicates that it provides victory points, place the card in a shared victory pile instead of discarding it.
     If the combat test fails, no damage is dealt to the attacked enemy. However, if an investigator fails a combat test aginst an enemy engaged with another investigator, the damage value of the failed attack is instead dealt to the investigator engaged with that enemy.
*** The Enemy Phase
    Resolve the following steps, in order. If there are no enemies in play, proceed to the upkeep phase.
    1. *Hunter enemies move.* Some enemies have the hunter keyword. Each such enemy moves once, to a connecting location, in the direction of the nearest investigator. Exhausted hunter enemies and hunter enemies at a location with one or more investigators do not move.
       If a hunter enemy moves to a location with one or more investigators, that enemy immediately engages one of those investigators. 
    2. *Enemy attacks.* Each ready, engaged enemy makes an attak agains the investigator with which it is engaged. The investigators resolve enemy attacks in player order. When an enemy attacks, deal both its damage and its horror, simultaneously, to the engaged investigator.
       The amount of damage and horror dealt by an enemy's attack can be found at the bottom of the enemy's text box.
       After an enemy attacks during the enemy phase, exhaust it to indicate that it has attacked. (During attacks of opportunity, enemies do not exhaust)
**** Damage and Horror
     An investigator may be dealt damage and/or horror during a scenario. Damage depletes an investigator's health, and horror depletes an investigator's sanity.
     When an investigator is dealt damage, place damage on the investigator card and/or on any of that investigator's asset cards taht have health, up to the amount of damage each card can hold. A card that has no health value cannot be dealt damage.
     When an investigator is dealt horror, place horror on the investigator card and/or on any of that investigator's asset cards that have sanity, up to the amount of horror each card can hold. A card that has no sanity value cannot be dealt horror.
     if a card has an amount of damage that equals or exceeds its health, or an amount of horror that equals or exceeds its sanity, the card is defeated. A defeated asset card is discarded. A defeated investigator is eliminated.
*** The Upkeep Phase
    Resolve the following steps, in order:
    1. Each investigator turns his or her mini card faceup.
    2. Ready all exhausted cards. Each unengaged enemy that readies at the same location as an investigator engages at this time.
    3. Each investigator draws 1 card and gains 1 resource.
    4. Each investigator with *more than 8 cards in his or her hand* chooses and discards cards from their hand until only 8 cards remain.
    After the above steps are complete, the game round is over. Proceed to the mythos phase of the next game round.
*** The Mythos Phase
    The mythos phase comprises three steps, described below.
    1. Place one doom token on the current agenda.
    2. Compare teh total number of doom tokens in play (on the current agenda and on other cards in play) to the doom threshold of the current agenda. If the number of doom tokens in play is equal to or greater than the doom threshold of the current agenda, advance the agenda deck. This is done by discarding all doom tokens from play, turning the current agenda card over, following the instructions on its reverse side, and removing that agenda from play. After following those instructions, the front side of the next card in the agenda deck becomes the active agenda card. (*Important Note:* Unless a card specifies that it can advance the agenda, this is the only time the agenda can advance.)
    3. In player order, each investigator draws the top card of the encounter deck. Instructions for resolving each type of encounter card are presented as treachery or enemy cards.
    *Treachery* - When a treachery card is drawn, its ability is resolved, and the card is placed in the encounter discard pile.
    *Enemy* - When an enemy card is drawn, that enemy spawns engaged with the investigator who drew the card, unless it has a "Spawn" instruction.If the enemy has a spawn instruction, it spawns at the location indicated by that instruction.
**** Enemy Engagement
      While an enemy card is in play, either it is engaged with an investigator (and placed in that player's threat area), or it is at a location (and placed at that location). Each enemy in an investigator's threat area is considered to be at the same location as that investigator. Should the investigator move, the enemy remains engaged with the investigator and also moves to the new location.
      Any time a ready non-engaged enemy is at the same location as an investigator, it engages that investigator and is placed in that investigator's threat area. If multiple investigators are at the same location as a ready enemy, the lead investigator chooses which of those investigators the enemy engages. some enemies also have a "*Prey*" instruction, which dictates whom it engages if there is a conflict. 
      An enemy will immediately engage if:
      - It spawns (in a ready state) at the same location as an investigator.
      - It moves (in a ready state) to the same location as an investigator.
      - An investigator moves to the same location as a ready enemy.
      - An exhausted enemy is readied at the same location as an investigator.
** What's Next?
   After the mythos phase is resolved, play proceeds to the investigator phase as usual. Continue resolving game rounds until players have reached the scenario's resolution. 
   After you've completed the game, you may wish to continue the campaign. To do so, read "Expanded Campaign Rules" in the Campaign Guide. Then proceed to the scenario "The Midnight Masks" using setup rules in the Rules Reference.
   Some players may with to practice using different investigators before proceeding to the campaign. To do so, use the Custom Deckbuilding rules. 
*** Custom Deckbuilding
    The /Arkham Horror: LCG/ core set is desinged to be a complete game experience with significant replayability. After learning the basics of the game, players may wish to explore building original decks.
**** Why Build a Custom Deck?
     Deckbuilding is a process by which a player may customize his or her deck to take on the scenarios using original strategies and ideas. This allows a player to experience the game in new ways; instead of adapting his or her play to the strategy of a starter deck, each player may construct a deck that functions as he or she desires. When a player constructs an original deck, that player doesn't just participate in the game: he or she actively shapes how it is played.
**** Deck Customization Rules
     The following are the deck customization rules for /Arkham Horror: LCG/ investigator decks. Note that for more deckbuilding options, players may want to obtain other expansion sets containing new cards.
     - A player must choose exactly 1 investigator card.
     - A player's investigator deck must include the exact number of standard player cards indicated on the back of his or her investigator card as the "Deck Size." For each of the investigators in the core set, this number is 30. Weakness, investigator-specific cards, and scenario cards that are added to a player's deck do not count toward this number.
     - Each standard player card in a player's deck must be chosen in observance with the "Deckbuilding Options" available on the back of his or her investigator card.
     - A player's deck cannot include more than 2 copies (by title) of any given player card.
     - Any other "Deckbuilding Requirements" on the back of a player's investigator card must be observed.
     - At the beginning of a campaign, an investigator may only include level 0 cards in his or her deck.
**** Random Weakness
     Most investigators have a deckbuilding requirement that instructs the player to add a random basic weakness to his or her deck.
     A basic weakness is identified by the weakness symbol.
     To select a random basic weakness, take a set of the ten bsic weaknesses in the core set, shuffle those weaknesses together, and draw one at random to add to the investigator's deck. Some /Arkham Horror: LCG/ products add additional basic weakness cards to a player's collection. Simply add these cards to the ten cards found in the core set when selecting random basic weaknesses in the future.
     The weakness selected via the process described above is added to the player's deck at the end of the deckbuilding process, after all other cards in the player's deck have been selected. In campaign mode, the selected weakness remains a part of the investigator's deck for the entire campaign, unless it is removed by a card ability. New weaknesses are not automatically added at the beginning of subsequent campaign scenarios, but card abilities or scenario instructions may instruct an investigator to gain additional weaknesses.
* Rules Reference
  This document is indended as the definitive source for rules information, but does not teach players how to play the game. Players should first read the Learn to play book it its entirety and use this Rules Reference as needed while playing the game.
  The majoirty of this guide consists of a glossary, which provides an alphabetical listing of terms and situations a player might encounter during a game. This section should be the first destination for players who have a rules question.
  The latter part of this guide contains four appendicies. The first appendix describes the process of playing cards or initiating triggered abilities. The second appendix provides timing diagrams that illustrate the structure of a game round, as well as a detailed explanation of how to handle each game step presente in those diagrams. The third appendix lists the complete rules for setting up a game of Arkham Horror: The Card Game. The fourth appendix provides a detailed anatomy of each cardtype.
** The Golden Rules
   If the text of this Rules Refrence directly contradicts the text of the Learn to Play book, the text of the Rules Reference takes precedence.
   If the text of a card directly contradicts the text of either the Rules Reference or the Learn to Play book, the text of the card takes precedence.
** The Grim Rule
   If players are unable to find the answer to a rules or timing conflict in the Rules Reference, resolve the conflict in the manner that the players percieve as the worst possible at that moment with regards to winning the scenario, and continue with the game.
** Glossary
   The following is an alphabetical list of entries for game rules, terms and situations that may occur duing play.
*** A, An
    When used to describe a condition, the words "a" or "an" are satisfied if one or more of the conditional elements are present. /For example, an investigator with 3 resources will satisfy the condition of "Each investigator with a resource"./
*** Ability
    An ability is the specialized game text that indicates how a card affects the game.
    - Card abilities only interact with the game if the card bearing the ability is in play, unless the ability (or rules for the cardtype) specifically references its use from an out-of-play area.
    - Car abilities only interact with other cards that are in play, unless the ability specifically references an interaction with cards in an out-of-play area.
    - If multiple instances of the same ability are in play, each instance interacts with (or may interact with) the game state individually.
    The various types of card abilities are: CA (Constant Abilities), FA (Forced Abilities), RA (Revelation Abilities), TA (Triggered Abilities), Keywords, and Enemy Instructions.
**** Constant Abilities (CA)
     Constant abilities are simply stated on a card with no special formatting. CA's are always interacting with the game state as long as the card is in play. (Some CA's continuously seek a specific condition, denoted by words such as "during" or "while". The effects of such abilities are active any time the specified condition is met). CA's have no point of initiation.
**** Forced Abilities (FA)
     A forced ability is identifed by a bold "*Forced*" command. Forced abilities initiate and interact with the game state automatically at a specified timing point. Such a timing point is usually indicated by words such as: "when", "after", "if", or "at".
     - If a forced ability does not have the potential to change the game state, the ability does not initiate.
     - The initiation of a forced ability that has the potential to change the game state is mandatory each time a specified timing point is met.
     - A forced ability with a timing point beginning with the word "when" automatically initiates as soon as the specified timing point is reached, but before its impact upon the game state is resolved. 
     - A forced ability with a timing point beginning with the word "after" automatically initiates immediately after that timing point's impact upon the game state is resolved. 
     - For any given timing point, all forced abilities initiated in reference to that timing point must resolve before any Triggered Abilities (TA) referencing the same timing point in the same manner may be initiated.
**** Revelation Abilities (RA)
     A revelation ability, indicated by a bold "*Revelation*" command on an encounter card or weakness, initiates as that card is drawn by an investigator.
**** Triggered Abilities (TA)
     A triggered ability is any ability prefaced by either an Free (F) (Bolt), Reaction (R) (Circular Arrow), or Action (A) (Arrow) icon. If the ability has one or more prerequisites, these are listed in text immediately following the icon. A player must always meet the prerequisites of a triggered ability in order to trigger that ability. There are three types of triggered abilities:
     Free triggered abilities (*FTA*) (Bolt) - An FTA may be triggered as a player ability during any player window (see Appendix 2).
     Reaction triggered abilities (*RTA*) (Circular Arrow) - An RTA with a specific triggering condition may be triggered any time a specific condition is met. 
     - An RTA with a triggering condition beginning with the word "when" may be used after the specific triggering condition initiates, but before its impact upon the game state resolves.
     - An RTA with a triggering condition beginning with the word "after" may be used immediately after that triggering condition's impact upon the game state has resolved.
     - Each RTA may be triggered only once each time the specified condition on the ability is met.
     Action triggered abilities (*ATA*) (Arrow) - An ATA may be triggered during a player's turn in the investigation phase through the use of the activate action, and only if the player uses one action for each ATA specified in the ability's cost.
     All triggered actions are governed by the following rules:
     - TAs on a card a player controls are optionally triggered (or not) by that player at the appropriate timing moment, as indicated by the ability.
     - A TA can only be initiated if its effect has the potential to change the game state, and its cost (if any) has the potential to be paid in full, taking active cost modifiers into account. This potential is assessed without taking into account the consequences of the cost payment or any other ability interactions.
     - Once an ability is initiated, players must resolve as much of the effect as possible, unless the effect uses the word "may".
**** Keywords
     A keyword is a card ability which conveys specific rules to its card.
**** Spawn Instructions and Prey Insructions
     Spawn instructions inform where an enemy spawns as it enters play.
     Prey instructions inform which investigator an enemy pursues and/or engages if it has a choice.
**** Action Designators
Some abilities have bold action designators (such as Fight, Evade, Investigate, or Move). Activating such an ability performs the designated action as described in the rules, but modified in the manner described by the ability.
*** Act Deck and Agenda Deck
    The act deck represents the progress the investigators can make in a scenario. The agenda deck represents the progress and objectives of the dark forces arrayed against the invesetigators in a scenario. Generally, advancing the act deck is good for the investigators, and advancing the agenda deck is bad for the investigators.
    - The act deck advances if the investigators, as a group, spend the requisite number of clues (as indicated by the act card). An act card may indicate a flat value (such as "4") or a per investigator value as (as indicated by the Inv icon). This is normally done as a FTA player ability. Any or all investigators may contribute any number of clues towards the total number of clues required to advance the act. If the act has an " *Objective* " instruction, that instruction overrides or adds additional requirements to the spending of those clues.
    - The agenda deck advances if the requisite number of doom is in play (doom on the agenda card as well as doom on any other cards in play), as indicated by the agenda card. An agenda card may indicate a flat value or a per investigator value. If the agenda has an " *Objective* " instruction, that instruction overrides or adds additional requirements to meeting this doom requirement.
    - The act/agenda on top of the act/agenda deck is referred to as the "current" act/agenda.
    To advance the act deck or the agenda deck, follow these steps, in order:
    1. Remove all tokens from the card to be advanced. If the agenda deck is advancing, remove all doom from each card in play.
    2. Flip the advancing card over and follow the instructions on the reverse ("b") side.
       - If the reverse side of the act or agenda is an encounter card, follow the rules for drawing that encounter cardtype. Otherwise, simply follow the instructions on the card.
    3. Sometimes, the advancing act/agenda specifies which card becomes the next act/agenda. If it does not, the next card in the deck becomes the current act/agenda. As a new card becomes the current act/agenda, the advancing card is simultaneously removed from the game.
       - Some instructions in the act and agenda decks (as well as on other encounter cardtypes) contain resolution points, in the format of: "( *R* )". If a resolution point is reached, the scenario ends. Read the designated resolution in the campaign guide.
    See also: "Clues" and "Doom"
*** Action
    During his or her turn, an investigator is permitted to take up to *three* actions. When performing an action, all costs of the action are first paid. Then, the consequences of the action resolve.
    - If an investigator is instructed to lose 1 or more actions, he or she has that many fewer actions to take during that round.
    For a complete list of available actions, see "Timing and Gameplay"
*** Activate Action
    "Activate" is an action an investigator may take during his or her turn in the investigation phase.
    When this action is taken, the investigator initiates an ability that specifies one or more ATA icons as part of its ability cost. The number of ATA icons in the ability's cost determines how many actions the investigator is required to use for this activate action. When performing an activate action, all of that action's costs are simultaneously paid. Then, the consequences of that action resolve.
    An investigator is permitted to activate abilities from the following sources:
    - A card in play and under his or her control. This includes his or her investigator card.
    - A scenario card that is in play and at the same location as the investigator. This includes the location itself, encounter cards placed at that location, and all encounter cards in the threat area of any investigator at that location.
    - The current act or agenda card.
*** Active Player
    The active player is the player taking his or her turn during the investigation phase.
*** After
    The word "after" refers to the moment immediately after the specified timing point or triggering condition has fully resolved.
    /(For example, an ability card that reads "After you draw an enemy card" initiates immediately after resolving all of the steps for drawing an enemy - resolving its revelation ability, spawning it, etc.)/
    See also: "Ability" "Priority of Simultaneous Resolution"
*** Agenda Deck
    See Act Deck and Agenda Decks
*** Aloof
    Aloof is a keyword ability. An enemy with the aloof keyword does not automatically engage investigators at its location.
    - When an aloof enemy spawns, it spawns unengaged.
    - An investigator may use the engage action or a card ability to engage and aloof enemy.
    - An investigator cannot attack an aloof enemy while that enemy is not egaged with an investigator.
*** Asset Cards
    Asset cards represent items, allies, talents, spells, and other reserves that may assist or be used by an investigator during a scenario.
    - When you play an asset, it is placed in your play area. Generally, assets remain in play unless discarded by a card ability or game step.
    - Some assets have health and/or sanity. When an investigator is dealt damage or horror, that investigator may assign some or all of that damage or horror to eligible asset cards he or she controls.
    - Most assets take up or more slots while in play.
    - Some assets have an encounter set icon and no level indicator. Such assets are known as Story Assets. Story Assets are part of an encounter set and may not be included in a player's deck unless the resolution or setup of a scenario grants that player permission to do so.
*** Attach To
    If a card uses the phrase "attach to" it must be attached to the specified game element as it enters play. Once attached, such a card is referred to as an attachment.
    - The "attach to" phrase is checked for legality each time a card would be attached to a game element, but is not checked again after that attachment occurs. If the initial "attach to" check does not pass, the card is not able to be attached, and remains in its prior state or game area. If such a card cannot remain in its prior state or game area, discard it.
    - Once in play, an attachment remains attached until either the attachment or the game element to which it is attached leaves play (in which case the attachement is discarded), or unless a card ability explicitly detaches the card.
    - An attachment exhausts and readies independently of the game element it's attached to.
*** Attacker, Attacked
    An "attacker" is an entity (usually an enemy or investigator) that is resolving its attack agains another entity. The entity being attacked is referred to as the "attacked enemy" or the "attacked investigator". 
*** Attack of Opportunity
    Each time an investigator is engaged with one or more ready enemies and takes an action other than to *fight*, to *evade*, or to activate a *parley* or *resign* ability, each of those enemies makes an attack of opportunity agains the investigator, in the order of the investigator's choosing. Each attack deals that enemy's damage and horror to the investigator.
    - An attack of opportunity is make immediately after all costs of initiating the action that provoded the attack have been paid, but before the application of that action's effect upon the game state.
    - An ability that costs more than one action only provokes one attack of opportunity from each engaged enemy.
    - An enemy does not exhaust while making an attack of opportunity.
    - After all attacks of opportunity are made, continue with the resolution of the action which investigated the attack.
    - Attacks of opportunity count as enemy attacks for the purposes of card abilities.
*** Automatic Failure/Success
    Some card or token abilities may cause a skill test to automatically fail or to automatically succeed. If a skill test automatically fails or automatically succeeds, it does so during step "ST.6" of the "Skill Test Timing" process.
    - If a skill test automatically fails, the investigator's total skill value for that test is considered 0.
    - If a skill test automatically succeeds, the total difficulty of that test is considered 0.
*** Base Value
    Base value is the value of an element before any modifiers are applied. Unless otherwise specified, the base value of an element derived from a card is the value printed on that card.
*** Bearer
    The bearer of a weakness is the investigator who started the game with the weakness in his or her deck or playing area.
    See also: "Weakness"
*** Blank
    If a card's printed text is considered "blank" by an ability, that text box is treated as if it did not have any of its printed content. Text and/or icons gained from another source are not blanked.
    - A card's text box includes: traits, keywords, card text and abilities.
*** Campaign Play
    A campaign is a series of interrelated scenarios in which each player plays the same investigator from one scenario to the next. As a campaign progresses, the investigator gains experience and trauma, and this is reflected by changes in his or her deck. Each decision make in a campaign may have repercussions in a later scenario.
    When starting a campaign, follow the instructions for that campaign's setup in the campaign guide. After playing through a scenario during a campaign, record the specified results of that scenario in the campaign log.
**** Experience
     After recording the results of a scenario, the investigators are ready to reflect on their experiences and purchase new cards for their decks. To do this, follow thse steps, in order:
     1. Count experience. Each investigator earns experience equal to the total victory value of all cards in the victory display plus or minus any bonuses or penalties indicated by the campaign guide for that resolution. This total is added to any unspend experience an investigator has recorded from previous scenarios in this campaign.
     2. Purchase new cards. New cards may be purchased and added to a player's deck by spending experience equal to the card's level (denoted by a number of pips in the upper left hand corner of the card). While purchasing new cards, observe the following rules:
	- An investigator's deckbuilding guidelines (found on the back of the investigator card) must be observed while that investigator is purchasing new cards. Only cards the investigator has access to may be purchased. The deck-size requirements must also be maintained, so that for each (non-permanent) card purchased and added to a deck, a different card is removed from the deck. Weakness cards and cards that must be included in an investigator's deck may not be removed while that investigator is purchasing new cards.
	- Each card costs experience equal to the card's level, /to a minimum of 1/ (purchasing a level zero card still costs 1 experience). The number of pips beneath a card's cost indicates the card's level.
	- When purchasing a higher level version of a card with the same title, the investigator may choose to "upgrade" that card by paying only the difference in experience (to a minimum of 1) between the two cards and removing the lower level version of the card from his or her deck.
	- New cards are purchased (or upgraded) individually. If an investigator wishes to purchase more than 1 copy of a new card, each copy must be paid for separately, and one card must be removed from that investigator's deck for each copy purchased.
	- The above processes, and any specific instructions provided by the campaign guide, are the only methods by which a player may modify his or her deck during a campaign.
**** Trauma
     Trauma reflects permanent damage that has been done to an investigator's health and/or psyche.
     If an investigator is defeated in a scenario that investigator is eliminated from the scenario but not necessarily from the campaign.
     I fan investigator is defeated by taking damage equal to his or her health, he or she suffers 1 physical trauma (recorded in the campaign log). For each physical trauma an investigator has, taht investigator begins each subsequent scenario in the campaign with 1 damage. If an investigator has physical trauma equal to his or her printed health, the investigator is *killed*.
     If an investigator is defeated by taking horror equal to his or her sanity, he or she suffers 1 mental trauma (recorded in the campaign log). For each mental trauma an investigator has, that investigator begins each subsequent scenario in the campaign with 1 horror. If an investigator has mental trauma equal to his or her printed sanity, the investigator is driven *insane*.
     If an investigator is defeated by simultaneously taking damage equal to his or her health /and/ horror equal to his or her sanity, he or she chooses which type of trauma to suffer.
     If an investigator is killed or driven insane, that player must choose a new investigator to use in the next scenario, and creates a new deck for that investigator. Investigators that are killed or driven insane cannot be used for the remainder of the campaign.
     If a player attempts to choose a new investigator and there are not investigators remaining in the pool, the players have lost and the campaign ends.
     See also: "Killed/Insane Investigators"
**** Defeat by Card Ability
     An investigator may be defeated by a card ability. A defeated investigator is eliminated from the game. Should this occur, follow the instructions on the card ability to determine if there are any long-term repercussions of the defeat.
**** Advancing to Next Scenario
     After completing a scenario, resolving its resolution, updating the campaign log, and purchasing any new cards, advance to the next scenario (sequentially) in the campaign, unless the scenario resolution explicitly directs the investigators to a different scenario.
**** Joining or Leaving a Campaign
     Once a campaign has begun, players can freely drop in and out of the campaign in between scenarios.
     If a player leaves the campaign, do not delete that palyer's information from the campaign log, as he or she may re-join at any time between scenarios.
     If a new player joins the campaign, he or she must choose an investigator not previously used during this campaign. That player begins as if it were his or her first scenario in the campaign, with no experience and no trauma.
*** Cancel
    Some card abilities can "cancel" other card or game effects. Cancel abilities interrupt the initiation of an effect, and prevent the effect from initiating.
    - Any time the effects of an ability are canceled, the ability (apart from its effects) is still regarded as initiated, and any costs have still been paid. The effects of the ability, however, are prevented from initiating and do not resolve.
    - If the effects of an event card are canceled, the card is still regarded as played, and it is still placed it its owner's discard pile.
    - If the effects fo a treachery card are canceled, the card is still regarded as having been drawn, and it is still placed in the encounter discard pile.
*** Cannot
    The word "cannot" is aboslute, and cannot be countermanded by other abilities.
*** Cardtypes
    The game's cardtypes are presented in Appendix 4, with detailed card anatomies.
    - If an ability causes a card to change its cardtype, it loses all other cardtypes it might possess and functions as would any card of the new cardtype.
    See also: "Asset Cards", "Enemy Cards", "Event Cards", "Location Cards", "Skill Cards", "Trechery Cards"
*** Chaos Tokens
    Chaos tokens are revealed from the chaos bag during skill tests, to modify or influence the results of the skill test.
    S (Skull), C (Cultist), O (Old One), T (Tablet) - If any of these tokens are revealed for a skill test, resolve the effect for that symbol as indicated on the scenario reference card for the current scenario.
    F (Failure) - This is the auto-fail token. If this token is revealed for a skill test, it indicates the investigator automatically fails the test.
    E (Elder Sign) - This is the elder sign token. If this token is revealed for a skill test, resolve the E effect on the investigator card belonging to the player performing the skill test.
    If a revealed chaos token (or the effect referenced by a chaos token) has a numerical modifier, that modifier is applied to the investigator's skill value for this test.
    See "ST.3 Reveal chaos token"
*** Clues
    Clues represent the progress the investigators can make towards solving a mystery, unraveling a conspiracy, and/or advancing in a scenario.
    - The first time an investigator enters a location, that location is revealed (turned face-up) and a number of clues equal to that location's clue value are placed on that location (from the token pool). Most clue values are conveyed as a "per investigator (INV)" value. This may occur during setup.
    - A clue at a location can be discovered by successfully investigating the location (see "Investigate Action"), or by a card ability. If an investigator discovers a clue, he or she takes the clue from the location and places it on his or her investigator card, under his or her control.
    - If there are no " *Objective* " requirements for advancing the current act, during any investigator's turn the investigators may, as a group, spend the requisite number of clues (usually conveyed as a "per investigator" value) from their investigator cards to advance the act deck. This is normally done as a FTA player ability. Any or all investigators may contribute any number of clues towards the total number of clues required to advance the deck.
    - A card ability that refers to clues "at a location" is referring to the undiscovered clues that are currently on that location.
    See also: "Act Deck and Agenda Deck", "Tokens, Running out of"
*** Collection
    If an ability refers to a player's collection (/for example, "search the collection"/ ), the collection of cards from which that player's deck was assembled is used.
    /Example: Sean and Etienne are each using a deck built from Sean's collection. If Etienne is instructed to "search the collection", he searches Sean's collection/
*** Constant Abilities
    See "Ability"
*** Control
    See "Ownership and Control"
*** Copy
    A copy of a card is defined by a title. A second copy fo a card is any other card that shares the same title, regardless of cardtype, text, artwork, or any other differeing characteristics between the cards.
*** Costs
    There are two types of costs in the game: resource costs and ability costs.
    A card's resource cost is the numerical value that must be paid (in resources) to play the card from hand. To pay a resource cost, an investigator takes the specified number of resources from his or her resource pool and places them in the token pool.
    Some triggered abilities are presented in a "cost:effect" construct. In such a construct, the aspect preceding the colon indicates the ability cost that must be paid and any triggering conditions that must be met to trigger the ability. The aspect following the colon is the effect.
    - If multiple costs for a single card or ability require payment, those costs must be paid simultaneously.
    - Only the controller of a card or ability may pay its costs. Game elements another player controls may not be used to pay a cost.
    - When exhausting, sacrificing, or otherwise using cards to pay costs, only cards that are in play and under their owner's control may be used, unless the cost specifies an out-of-play state.
    - If a cost requires a game element that is not in play, the player paying the cost may only use game elements that are in his or her hame areas (such as his or her hand or deck) to pay the cost.
    - If the investigators are instructed to pay a cost as a group, each investigator (or each investigator in the group defined by the ability) may contribute to paying the cost.
    - An ability cannot initiate - and therefore its cost cannot be paid - if the resolution of its effect will not change the game state.
    - If an investigator takes damage or horror as a cost and reassigns any of it to an asset, the cost is still considered paid.
*** Dealing Damage/Horror
    There are two types of afflictions that may beset an investigator in the game: damage and horror. Damage afflicts an investigator's health, and horror afflicts an investigator's sanity.
    When an investigator or enemy is dealt damage and/or horror, follow these steps, in order:
    1. *Assign Damage/Horror*: Determine the amount of damage and/or horror being dealt. Place damage and/or horror tokens equal to the amount of damage and horror being dealt next to the cards that will be taking the damage/horror.
       - When an invsetigator is dealt damage or horror, that investigator may assign it to eligible asset cards he or she controls. To be eligible, an asset card must have health in order to be assigned damage, and it must have sanity in order to be assigned horror.
       - An asset cannot be assinged damage beyond the amound of damage it would take to defeat the card, and cannot be assigned horror beyond the amount of horror it would take to defeat the card.
       - All damage/horror that cannot be assigned to an asset must be assinged to the investigator.
    2. *Apply Damage/Horror* Any assigned damage/horror that has not been prevented is now placed on each card to which it has been assigned, simultaneously. If no damage/horror is applied in this step, no damage/horror has been successfully dealt.
       - Abilities that prevent, reduce, or reassign damage and/or horror that is being dealth are resolved between steps 1 and 2.
       - After applying damage/horror, if an investigator has damage equal to or higher than his or her health or horror equal to or higher than his or her sanity, he or she is defeated. When an investigator is defeated, he or she is eliminated from the scenario (see "Elimination").
       - After applying damage/horror, if an enemy has damage equal to or higher than its health, it is defeated and placed in the encounter discard pile (or in its owner's discard pile if it is a weakness).
       - After applying damage/horror, if an asset has damage equal to or higher than its health or horror equal to or higher than its sanity, it is defeated and placed in its owner's discard pile.
*** Deck
    There are 4 main types of decks that appear in any game: the Investigator Deck, the Encounter Deck, the Act Deck, and the Agenda Deck.
    - The order of cards within a deck may not be altered unless a player is instructed to by a card ability.
    See also: "Investigator Deck", "Encounter Deck", Act Deck and Agenda Deck"
*** Deckbuilding
    When building a custom deck, the following guidelines must be observed:
    - A player must choose exactly 1 investigator card
    - A player's investigator deck must include the exact number of cards indicated on the back of his or her investigator card as the "Deck Size". Weaknesses, investigator-specific cards, and scenario cards that are added to a player's deck do not count towards this number.
    - A player's investigator deck may not include more than 2 copies (by title) of any given player card.
    - Each standard player card in a player's investigator deck must be chosen from among the "Deckbuilding Options" aviailable on the back of his or her investigator card.
    - Most investigators have 0 experience to spend at the beginning of a campaign, which means that they may only include level 0 cards in their decks. Some investigators and/or some campaigns, may provide a player with additional experience at the beginning of a campaign, which can be used immediately to purchase higher level cards.
    - All other "Deckbuilding Requirements" listed on the back of a player's investigator card must be observed.
    - Each required random basic weakness is added to a player's deck at the end of the deckbuilding process.
    - Story Assets may not be included in a player's deck unless the setup or resolution of a scenario grants that player permission to do so. These assets are indicated by the lack of a card level and the presence of an encounter set symbol.
    - During a campaign, players build a deck before playing the first scenario. In between scenarios, players can purchase new cards or upgrade cards in their deck following the rules found under "Campaign Play".
**** Classes
     Most player cards, including investigators, belong to one of the 5 classes. Each class has its own distinct flavor and identity, as described below.
     *Guardians* (G) feel compelled to defend humanity, and thus go out of their way to combat the forces of the Mythos. They have a strong sense of duty and selflessness that drives them to protect others, and to hunt monsters down.
     *Mystics* (M) are drawn to and influenced by the arcane forces of the Mythos. Many have spell-casting abilities, able to manipulate the forces of the universe through magical talent.
     *Rogues* (R) are self-serving and out for themselves. Wily and opportunistic, they are always eager for a way to exploit their current situation.
     *Seekers* (Se) are primarily concerned with learning more about the world and about the Mythos. They wish to research forgotten lore, map out uncharted areas, and study strange creatures.
     *Survivors* (Su) are everyday people in the wrong place at the wrong time, simply trying to survive. Ill-prepared and ill-equiped, Survivors are the underdogs, who rise to the occasion when their lives are threatened.
     Some cards are not affiliated with any class; these cards are neutral.
     Generally, investigators only have access to cards from their class. Some investigators have access to cards from other classes. Refer to the "Deckbuilding Options" on the back of an investigator card to view which cards an investigator has access to.
*** Defeat
    Taking damage and/or horror may cause an investigator, enemy, or asset to be defeated.
    - If an investigator has as much or more damage on it as it has health (or as much or more horror on it as it has sanity), that investigator is defeated. An investigator might also be defeated by a card ability. When an investigator is defeated, he or she is eliminated from the scenario (see "Elimination").
    - In campaign play, an investigator that is defeated by taking damage equal to his or her health suffers 1 physical trauma. An investigator that is defeated by taking horror equal to his or her sanity suffers 1 mental trauma. Taking trauma may causae an investigator to be *killed* or driven *insane* (see "Campaign Play").
    - If an enemy has a much or more damage on it as it has health, that enemy is defeated and placed on the encounter discard pile (or on its owner's discard pile if it is a weakness).
    - If an asset with a health value has as much or more damage that it has health, it is defeated. If an asset with sanity value has as much or more horror that it has sanity, it is defeated. A defeated asset is placed on its owner's discard pile.
*** Delayed Effects
    Some abilities create delayed effects. Such abilities specify a future timing point, or indicate a future condition that may arise, and dictate an effect that will happen at that time.
    - Each delayed effect initiates automatically and immediately (as a forced ability) if its future timing point or future condition occurs.
    - A delayed effect affects all specified entities that are in the specified game area and eligible at the time the delayed effect resolves.
*** Difficulty (level)
    There are four levels of difficulty in /Arkham Horror: The Card Game:/ Easy, Standard, Hard, and Expert. At the beginning of a campaign or standalone scenario, the players choose which difficulty level to use. The campaign setup section of that campaign or scenario's Campaign Guide indicates which chaos tokens should be placed into the chaos bag when playing on each difficulty level.
    - When playing in Easy or Standard mode, use the "Easy/Standard" side of each scenario's reference card. When playing in Hard or Expert mode, use the "Hard/Expert" side of each scenario's reference card instead.
*** Difficulty (skill tests)
    The difficulty of a skill test is the target number an investigator is trying to equal or exceed with his or her modified skill value to pass that test.
    - When attacking an enemy, the base difficulty of the skill test is the enemy's fight value.
    - When investigating a location, the base difficulty of the skill test is the location's shroud value.
    - When attempting to evade an enemy, the base difficulty for the skill test is the enemy's evade value.
    - When resolving a skill test created by a card ability, the base difficulty is indicated as a parenthetical value following the indication of which skill is being tested. /For example: Intellect (3)/.
    Also see: "Skill Test Timing"
*** Direct Damage, Direct Horror
    If an ability causes a card to take direct damage or direct horror, that damage or horror must be assigned directly to the specified card, and cannot be assigned or re-assigned elsewhere.
*** Discard Piles
    Any time a card is discarded, it is placed faceup on top of its owner's discard pile. Encounter cards are owned by the encounter deck.
    - Each discard pile is an out-of-play area.
    - Each investigator has his or her own discard pile, and the encounter deck has its own discard pile.
    - Each discard pile is open information, and may be looked at by any player at any time.
    - The order of cards in the discard pile may not be altered unless a player is instructed to do so by a card ability.
    - If multiple cards are discarded simultaneously, the owner of the cards may physically place them on top of his or her discard pile one at a time, in any order. If multiple counter cards are discarded simultaneously, they are placed on top of the encounter discard pile in any order (determined by the lead investigator).
    - Any ability that would shuffle a discard pile of zero cards back into a deck does not shuffle the deck.
*** Doom
    Doom prepresents the progress the forces of the Mythos make towards completing foul rituals, summoning cosmic entities, and/or advancing a scenario's agenda.
    - During each Mythos phase, 1 doom is placed on the current agenda.
    - If there are no " *Objective* " requirements for advancing the current agenda and the requisite amount of doom is in play (among the agenda and all cards in play), the agenda advances during the "Check doom threshold" step of the Mythos phase. Unless a card otherwise specifies that it can advance the agenda, this is the only time at which the agenda can advance.
    - Doom on cards other than the agenda (such as enemies, allies, locations, etc.) counts towards the amount of doom in play.
    See also: "Act Deck and Agenda Deck", "Tokens, Running out of"
*** Draw Action
    "Draw" is an action an investigator may take during his or her turn in the investigation phase.
    When an investigator takes this action, that investigator draws one card from his or her deck.
*** Drawing Cards
    When a player is instructed to draw one or more cards, those cards are drawn from the top of his or her investigator deck and added to his or her hand.
    When a player is instructed to draw one or more encounter cards, those cards are drawn from the top of the encounter deck, and resolved following the rule for drawing encounter cards under frameworks step.
    - When a player draws two or more card as the result of a single ability or game step, those cards are drawn simultaneously. If a deck empties mid-draw, reset the deck and complete the draw
    - There is no limit to the number of cards a player may draw each round.
    - If an investigator with an empty investigator deck needs to draw a card, that investigator shuffles his or her discard pile back into his or her deck, then draws the card, and upon completion of the entire draw takes one horror.
*** Effects
    A card effect is any effect that arises from the resolution of ability text printed on, or gained by, a card. A frameword effect is any effect that arises from the resolution of a frameword event.
    - Card effects may be preceded by costs, triggering conditions, play restrictions, and/or play permissions; such elements are not considered effects (see "Ability").
    - Once initiated, players must resolve as much of each aspect of the effect as they are able, unless the effect uses the word "may".
    - When a non-targeting effect attempts to interact with a number of entities (such as "draw 3 cards" or "search the top 5 cards of your deck") that exceeds the number of entities that currently exist in the specified game area, the effect interacts with as many entities as possible.
    - The expiration of a lasting effect (or the cessation of a constant ability) is not considered to be generating a game state change by a card effect.
    - All aspects of an effect have timing priority over all "after..." triggering conditions that might arise as a consequence of that effect. /(For example, if an effect reads "Gain 3 resources and draw 3 cards," resolve both aspects of the effect (gaining resources and drawing cards) before initiating an ability that reads "After drawing a card...")/
    - See also: "Delayed Effects", "Lasting Effects", "Priority of Simultaneous Resolution"
*** Elimination
    A player is eliminated from a scenario any time his or her investigator is defeated, or if he or she resigns. The only manner in which eliminated investigators interact with the game when establishing "per investigator" values. Any time a player is eliminated:
    1. The cards he or she controls in play and all of the cards in his or her out-of-play areas (such as hand, deck, discard pile) are removed from the game.
       - Any card that player owns but does not control that is in play remains in play, but if that card leaves play it is removed from the game.
    2. All clue tokens that player possesses are placed at the location the investigator was at when he or she was eliminated, and all of that player's resource tokens are returned to the token pool.
    3. All enemies engaged with that player are placed at the location the investigator was when he or she was eliminated, unengaged but otherwise maintaining their current game state.
    4. All other cards in the eliminated investigator's threat area are placed in the appropriate discard pile.
    5. If the lead investigator is eliminated, the remaining players (if any) choose a new lead investigator.
    6. If there are no remaining players, the scenario ends. Refer to "no resolution was reached" antry for that scenario in the campaing guide.
*** Empty Location
    An empty location is a location with no enemies or investigators at it.
*** Encounter Deck
    The encounter deck contains the enctounter cards (enemy, treachery, and story asset cards) the investigators may encounter during a scenario.
    - If the encounter deck is empty, shuffle the encounter discard pile back into the encounter deck.
*** Encounter Sets
    An encounter set is a collection of encounter cards, denoted by a common encounter set symbol near each card's cardtype.
*** Enemy Cards
    Enemies represent villains, cultists, ne'er-do-wells, terrible monsters, and unfathomable entities from alternate dimensions or the cosmos beyond.
    When an enemy card is drawn by an investigator, that investigator must spawn it following any spawn direction the card bears. If the encountered enemy has no spawn direction, the enemy spawns engaged with the investigator encountering the card and is placeds in that investigator's threat area.
    See "1.4 Each investigator draws 1 encounter card"
    - A ready, unengaged enemy engages any time it is at the same location as an investigator (see "Enemy engagement")
    - If an investigator is engaged with a ready enemy and takes an action other than to *fight*, to *evade*, or to activate a *parley* or *resign* ability, that enemy makes an attack of opportunity (see "Attack of Opportunity").
    - Enemies with the hunter keyword move during the Enemy Phase (see "III. Enemy phase").
    - Engaged enemies attack during the Enemy Phase (see "III. Enemy phase").
*** Enemy Engagement
    While an enemy card is in play, it is either engaged with an investigator (and placed in that investigator's threat area), or it is unengaged and at a location (and placed at that location). Each enemy in an investigator's threat area is considered to be at the same location as that investigator, and should the investigator move, the enemy remains engaged and moves to the new location simultaneously with the investigator.
    Any time a ready unengaged enemy is at the same location as an investigator, it engages that investigator, and is placed in that investigator's threat area. If there are multiple investigators at the same location as a ready unengaged enemy, follow the enemy's prey instructions to determine with investigator is engaged. There is no limit on the number of enemies that can be engaged with a single investigator.
    /For example, a ready unengaged enemy immediately engages if:/
    - /It spawns at the same location as an investigator/
    - /It moves into the same location as an investigator/
    - /An investigator moves into the same location as it./
    An exhausted unengaged enemy does not engage, but if an exhausted enemy at the location as an investigator becomes ready, it engages as soon as it is readied.
    - /Note: An enemy with the Aloof keyword does not engage in the manner described above./
*** Enemy Phase
    See Enemy Phase
*** Engage Action
    "Engage" is an action an investigator may take during his or her turn in the investigation phase.
    To engage an enemy at the same location /(for example, this could be done to engage an eshausted enemy, an aloof enemy, or an enemy enaged with another investigator)/, an investigator places the chosen enemy in his or her threat area. The investigator and the enemy are now engaged.
    - An investigator may perform the engage action to engage an enemy that is engaged with a different investigator at the same location. The enemy simultaneously disengages from the previous investigator and engages the invstigator performing the action.
    - An investigator cannot use the engage action to engage an enemy he or she is already engaged with.
*** Enters Play
    The pharse "enters play" refers to any time a card makes a transition from an out-of-play area into a play area (see In Play and Out of Play).
    - If an ability (either from the card itself or from another card) causes a card to enter play in a state different from that specified by the rules, there is no transition to that state. It merely enters play in that state.
*** Evade, Evade Action
    "Evade" is an action an investigator may take during his or her turn in the investigation phase.
    To evade an enemy engaged with an investigator, that investigator makes an agility test against the enemy's evade value (see Skill Tests).
    If the test is successful, the investigator successfully evades the enemy (see below).
    If the test fails, the investigator does not evade the enemy, and it remains engaged with him or her.
    - If an ability "automatically" evades 1 or more enemies, no skill test is make for the evasion attempt.
    - Any time an enemy is evaded (whether by an event action, or by card ability), the enemy is exhausted (if it was ready) and the engagement is broken. Move the enemy from the investigator's threat area to the investigator's location to mark that it is no longer engaged with that investigator.
    - Unlike the fight and engage action, an investigator can only perform an evade action against an enemy engaged with him or her.
*** Event Cards
    Event cards represent tactical actions, maneuvers, spells, tricks, and other instantaneous effects at a player's disposal.
    - If an event card does not have the fast keyword, it may only be played from a player's had by performing a "Play" action during his or her turn. You must follow all play permissions/restrictions that card has.
    - A fast event card may be played from a player's hand any time its play instructions specify (see "Fast")
    - Any time a player plays an event card, its costs are paid, its effects are resolved (or canceled), and the card is placed in its owner's discard pile after those effects resolve (or are canceled).
    - If the effects of an event card are canceled, the card is still considered to have been played, and its costs remain paid. Only the effects have been canceled.
    - Playing an event card from hand (or not playing it) is always optional for a player, unless the event uses the word "must" in its play instructions.
    - An event card cannot be played unless the resolution of its effect has the potential to change the game state.
*** Exceptional
    Exceptional is a deckbuilding keyword ability.
    - A card with the exceptional keyword cost twice its printed experience cost to purchase.
    - A player's investigator deck cannot include more than 1 copy (by title) of any given exceptional card.
*** Exhaust, Exhausted
    Occasionally, a card ability or game step will cause a card to exhaust to indicate it has been used to perform a function. When a card exhausts, it is rotated 90 degress. A card in this state is said to be exhausted.
    - An exhausted card cannot exhaust again until it is ready (typically by a game step or card ability.
*** Experience
    See Campaign
*** Fast
    Fast is a keyword ability. A fast card does not cost an action to be played and is not played using the "Play" action.
    - A fast event card may be played from a player's had any time its play instructions specify. If the instructions specify when/after a timing point, the card may be played as if the described timing point were a triggering condition for playing the card. If the instructions specify a duration or period of time, the card may be played during any player window within that period. If the instructions specify both a when/after timing point and a duration or period of time, the card may be played in reference to any instance of hte specified triggering condition within that time period.
    - A fast asset may be played by an investigator during any player window on his or her turn.
    - Because fast cards do not cost actions to play, they do not provoke attacks of opportunity (see "Attack of Opportunity").
*** Fight Action
    "Fight" is an action an investigator may take during his or her turn in the invstigation phase.
    To fight an enemy at his or her location, an investigator resolves an attack against that enemy by making a combat test against the enemy's fight value (see "Skill Tests").
    If the test is successful, the attack succeeds and damage is dealt to the attacked enemy. The default damage dealt by an attack is 1. Some weapons, spells, or other special attacks may modify this damage. (This occurs on step 7 of the skill test "Apply skill test results").
    If the test fails, no damage is dealt to the attacked enemy. However, if an investigator fails this test agains an enemy that is engaged with another single investigator, the damage of the attack is dealt to the investigator engaged with that enemy.
    - An investigator may fight any enemy at his or her location, including: an enemy he or she is engaged with, an unengaged enemy at the same location, or an enemy engaged with another investigator who is at the same location.
*** Flavor Text
    Flavor text is additional text that provides thematic context to a card and/or its abilities. Flavor text does not interact with the game in any manner.
*** Forced Abilities
    See "Ability"
*** Gains
    The word "gains" is used in multiple contexts.
    - If a player gains one or more resources, the player takes the specified number of resources from the token pool and adds them to his or her resource pool.
    - If an investigator gains an action, that investigator is permitted one additional action to spend during the specified time period.
    - If a card gains a characteristic (such as an icon, a trait, a keyword, or ability text), the card functions as if it possesses the gained characteristic.
    - "Gained" characteristics are not considered to be "printed" on the card. If an ability refers to the printed characteristics of a card, it does not refer to gained characteristics.
*** Game
    A 'game' consists of a single scenario, not an entire campaign. In a campaign, the beginning of a new scenario marks the start of a new game.
*** Hand Size
    See Upkeep Phase
*** Heal
    "Heal" is an instruction to remove the indicated amount of damage or the indicated amount of horror from a card.
    - If a card is healed for more damages or horror than it currently has on it, remove as much of the indicated amount as possible.
*** Health and Damage
    Health represents a card's physical fortitude. Damage tracks the physical harm that has been done to a card during a scenario.
    - Any time a card takes damage, place a number of damage tokens equal to the amount of damage just taken on the card (see Dealing Damage/Horror).
    - If an investigator has damage on him or her equal to or greater than his or her health, that investigator is defeated. When an investigator id defeated, he or she is eliminated from the scenario (see Elimination).
    - In campaign play, an investigator that is defeated by taking damage equal to his or her health suffers 1 physical trauma. Taking physical trauma may cause an invesitgator to be *killed* (see Campaign Play).
    - If an enemy has damage on it equal to or greater than its health, that enemy is defeated and placed in the encounter discard pile.
    - If an asset with a health value has damage on it equal to or greater than its health, it is defeated and placed on its owner's discard pile.
    - An asset card without a health value is not considered to have a health of 0, cannot gain health, and cannot have damage assigned to it.
    - A card's "remaining health" is its base health minus the amount of damage on it, plus or minus any active health modifiers.
    See also: Direct Damage, Direct Horror
*** Hunter
    Huter is a keyword ability.
    During the enemy phase, each ready, unengaged enemy with the hunter keyword moves to a connecting location, along the shortest path towards the nearest investigator. Enemies at a location with one or more investigators do not move.
    - If there are multiple equidistant investigators who qualify as "the nearest investigator," the enemy moves towards the one of those who best meets its prey instructions. If none do, or if the enemy has no prey instructions, the lead investigator may choose an investigator for the enemy to move towards.
    - If a hunter enemy would be compelled to a locaiton to which the move is blocked by a card ability, the enmy does not move.
    See Prey
*** Immune
    If a card is immune to a specified set of effects (/for example, "immune to treachery card effects," or "immune to player card effects"/), it cannot be affected by or chosen to be affected by effects belonging to that set. Only the card itself is protected, and peripheral entities associeated with an immune card (such as attached assets, tokens placed on, or abilities originating from and immune card) are not themselves immune. 
    - If a card gains immunity to an effect, pre-existing lasting effects that have been applied to the card are not removed. If a card loses immunity to an effect, pre-existing lasting effects of that nature are not applied to the card.
    - Immunity only protects a card from effects. It does not protect a card from costs.
*** In Play and Out of Play
    The cards that a player controls in his or her play area are considered in play.
    The current act, the current agenda, each location in the play area, and each encounter card in a investigator's threat area or a location, are all considered in play.
    Out of play refers to the cards in a player's hand, in any deck, in any discard pile, in the victory display, and those that have been set aside and/or removed from the game.
    - A card enters play when it transitions from an out-of-play origin to an in play area.
    - A card leaves play when it transitions from a in play area to an out-of-play destination.
    - Tokens on in play cards are considered in play. Resources in each investigator's resource pool are also considered in play.
*** In Player Order
    If the players are instructed to perform a sequence "in player order," the lead investigator performs his or her part of the sequence first, followed by the other players in clockwise order. The phrase "the next player" is used in this context to refer to the next player (clockwise) to act in player order.
*** Instead
    The word "instead" is indicative of a replacement effect. A replacement effect is an effect that replaces the resolution of a triggering condition with an alternate means of resolution.
    - If multiple replacement effects are initiated agains the same triggering condition and create a conflict in how to resolve the triggering condition, the most recent replacement effect is the one that is used for the resolution of the triggering condition.
    - The word "would" is used to define the triggering condition of some abilities, and establishes a higher priority for those abilities than abilities referencing the same triggering condition without the word "would". (For instance "When X would occur" resolves before "When X occurs")
    - If a replacement effect that uses the word "would" changes the nature of a triggering condition, the original triggering condition is replaced with the new triggering condition. No further abilities referencing the original triggering condition may be used.
*** Investigate Action
    "Investigate" is an action an investigator may take during his or her turn in the investigation phase.
    Each time an investigator takes this action, he or she makes an intellect test against the shroud value of that location (see Skill Tests).
    If the test is successful, the investigator has succeeded in investigating the location, he or she discovers one clue at the location. 
    Any time an investigator discovers a clue from a location, that player takes the clue from the location and places it on his or her investigator card, under his or her control.
    If the test is failed , the investigator has failed in investigating the locaiton. No clues are discovered during step 7 of the skill test.
*** Investigation Phase
    See Investigation Phase in gameplay
*** Investigator Deck
    A player's "investigator deck" is the deck that contains that player's asset, event, skill, and weakness cards. A reference to "your deck" refers to the investigator deck under your control.
*** Keywords
    A keyword is a card ability which conveys specific rules to its card. Each keyword has its own rules which can be found in the keyword's own section of the glossary. The keywords in this game are: aloof, fast, hunter, massive, peril, retaliate, surge, uses.
    - There are also two deckbuilding keywords: exceptional and permanent. Deckbuilding keywords affect deck customization while building and/or leveling up a deck. They have no effect during gameplay. There are no exceptional or permanent cards in the core set - each of these keywords will be presented in future expansions.
    - A single card that has and/or is gained the same keyword from multiple sources functions as if it has one instance of that keyword.
    - The initiation of any keyword which uses the word "may" in its keyword description is optional. The application of all other keywords is mandatory.
    See Ability
*** Killed/Insane Investigators
    During campaign play, investigators who are killed or driven insane must be recorded in your campaign log and cannot be used for the remainder of the campaign.
    - An investigator with physical trauma equal to or higher than his or her printed health is killed.
    - An investigator with mental trauma equal to or higher than his or her printed sanity is driven insane. 
    - An investigator may also be killed or driven insane by card ability, or during a scenario's resolution.
    - When playing a standalone scenario, there is no practical difference between being killed, driven insane, or defeated.
    See Campaign Play
*** Lasting Effects
    Some card abilities create conditions that affect the game state for a specified duration (/for example, "until the end of the phase" or "for this skill test"/). Such effects are known as lasting effects.
    - A lasting effect persists beyond the resolution of the ability that created it, for the duration specified by the effect. The effect continues to affect the game state for the specified duration regardless of whether the card that created the lasting effect is or remains in play.
    - If a lasting effect affects in-play cards (or cards in a specified area), it is only applied to cards that are in play (or the specified area) when the lasting effect is established. Cards that enter play (or the specified area) after its establishment are not affected by the lasting effect.
    - A lasting effect expires as soon as the timing point specified by its duration is reached. This means that an "until the end of the phase" lasting effect expires before an "at the end of the phase" ability or delayed effect may initiate.
    - A lasting effect that expires at the end of a specific time period can only be initiated during that time period.
*** Lead Investigator
    The lead investigator is sometimes required to make important scenario decisions. At the beginning of a scenario, the investigators choose a lead investigator. If they cannot agree on a choice, a lead investigator is chosen at random.
    - If there are ever multiple valid options for a choice or decision that must be made (/for example, a hunter enemy that could move in two different directions/), the lead investigator is the final arbiter in choosing among those options.
    - If the lead investigator is eliminated, the remaining players (if any) choose a new lead investigator. 
*** Leaves Play
    The phrase "leaves play" refers to any time a card makes a transition from an in-play state to an out-of-play state (see In Play and Out of Play).
    If a card leaves play, the following consequences occur simultaneously with the card leaving play:
    - All tokens on the card are returned to the token pool.
    - All attachments on the card are discarded.
    - All lasting effects and/or delayed effects affecting the card while it was in play expire for that card.
*** Limits and Maximums
    "*Limit X per [period]*" is a limit that appears on cards that remain in play through the resolution of an ability's effect. Each instance of an ability with such a limit may be initiated X times during the designated period. If a card leaves play and re-enters play during the same period, the card is considered to be bringing a new instance of the ability to the game. 
    "*Limit X per [card/game element]*" is a limit that appears on attachment cards, and restricts the number of copies of that card (by title) that can be attached to each designated card or game element.
    - Unless stated otherwise, limits are player specific.
    - A "group limit", however applies to the entire group of investigators. (/For example, if an investigator triggers an ability that is "group limit once per game", no other investigators may trigger that ability during that game/)
    "*Max X per [period]*" imposes a maximum across all copies of a card (by title) for all players. Generally, this phrase imposes a maximum number of times that copies of that card can be played during the designated time period. If a maximum includes the word "committed" (/For example, "Max 1 commited per skill test/), it imposes a maximum number of copies of that card that can be committed to skill test during the designated period. If a maximum appears as part of an ability, it imposes a maximum number of times that ability can be initiated from all copies (by title) of cards bearing that ability (including itself), during the designated period.
    If the effects of a card or ability with a limit or maximum are canceled, it is still counted against the limit/maximum, because the ability has been initiated.
*** Location Cards
    Location cards represent the places the investigators may explore during a scenario.
    - Use each investigator's mini-card to indicate which location he or she is at.
    - While an investigator is at a location, that investigator, each of his or her assets, and each card in that investigator's threat area is at the same location.
    - Locations enter play in an "unrevealed" state, so that the side with no shroud value and/or clue value is faceup. Do not read "revealed" side at this time.
    - The first time a location is entered by an invetigator, that location is revealed by turning it to its other side and placing a number of clues on it equal to its clue value (this may occur during setup). Most clue values are conveyed as a "per investigator" (Inv) value.
    - A location with its shroud/clue value side faceup is in the "revealed" state.
*** Massive
    Massive is a keyword ability. A ready enemy with the massive keyword is considered to be engaged with each investigator at the same location as it.
    - An exhausted enemy with the massive keyword is not considered to be engaged with any investigators.
    - An enemy with the massive keyword cannot be placed in an investigator's threat area.
    - When an enemy with the massive keyword attacks during the enemy phase, resolve its (full) attack against each investigator it is engaged with, one investigator at a time. The lead investigator chooses the order in which these attacks resolve. The massive enemy does not exhaust until its final attack of the phase resolves.
    - When an enemy with the massive keyword makes an attack of opportunity, that attack only resolves agains the investigator who provoked the attack.
    - A massive enemy does not move with an engaged investigator who moves away from the massive enemy's locaiton. 
    - If an investigator fails a combat test against a massive enemy, no damage is dealt to the engaged investigators.
*** May
    The word "may" indicates that a specified player has the option to do that which follows. If no player is specified, the option is granted to the controller of the card with the ability in question.
*** Modifiers
    Some abilities cause values or quantities of characteristics to be modified. The game state constantly checks and (if necessary) updates the count of any vaiable value or quantity that is being modified.
    Any time a new modifier is applied (or removed), the entire quantity is recalculated from the start, considering the unmodified base value and all active modifiers.
    - When calculating a value, treat all modifiers as being applied simultaneously. However, while performing the calculation, all additive and subtractive modifiers are calculated before doubling and/or halving modifiers.
    - Fractional values are rounded up after all modifiers have been applied.
    - A quantity on a card (such as a stat, an icon, a number of instances of a trait or keyword) cannot be reduced so that it functions with a value below zero. Negative modifiers in excess of a value's current quantity can be applied, but, after all active modifiers have been applied, any resultant value below zero is treated as zero. (/For example: Danny tests agility and reveals a -8 chaos token. When applied to his agility of 4, this would reduce his skill value to -4. However, his agility cannot be reduced so that it functions with a value below zero. While the -8 modifier still exists, his agility is treated as zero. If Danny were to play "Lucky!" to recieve a +2 bonus to the test, this bonus would not be applied to the functioning skill value of zero; but rather, it is applied in ocnjunction with all active modifiers. Danny's agility would then be calculated as follows: base skill 4, -8 from chaos token, +2 from "Lucky!" for a total of -2, which is still treated as zero/)
*** Move
    Any time an entity (an investigator or enemy) moves, transfer that enemy card or investigator's mini card from its current location to a different location.
    - Unless otherwise specified by the move effect or ability, the moving entity must move to a connecting location. Connecting locations are identified on the location card representing the entity's current location, as shown below.
    - Any time an entity moves, it is considered to leave the previous locaiton, and to enter the new location, simultaneously.
    - If an enemy is "moved to..." a specific location, the entity is moved directly to that location, and does not pass through other locations en route.
    - If an investigator moves to an unrevealed location, that location is revealed by turning it to its other side, and placing a number of clues on it equal to its clue value. Most clue values are conveyed as a "per investigator" (Inv) value.
    - If an enemy moves to an unrevealed location, that location remains unrevealed.
    - Game elements (tokens or cards) may also be moved by card abilities from one card to another, or from one game area to another game area.
    - When an entity or game element moves, it cannot move to its same (current) placement. If there is not valid destination for a move, the move cannot be attempted.
*** Move Action
    "Move" is an action an investigator may take during his or her turn in the investigation phase.
    When an investigator takes this action, move that investigator (using his or her mini card) to any other location that is markd a connecting location on his or her current location (see Move).
*** Mulligan
    After a player draws a starting hand during setup, that player has a single opportunity to declare a mulligan on any number of the drawn cards he or she does not wish to keep in his or her starting hand. These cards are set aside, and an equivalent number of cards are drawn and added to the player's starting hand. The set-aside cards are then shuffled back into the player's deck.
    - Players take or forgo the opportunity to mulligan in player order.
*** Must
    If an investigator is instructed that he or she "must" choose among multiple options, the investigator is compelled to choose an option that has the potential to change the game state.
    - In the absence of the word "must" while choosing among multiple options, any option may be chosen upon the resolution of the effect - even an option that does not change the game state.
*** Mythos Phase
    See Mythos Phase
*** Nearest
    Some card abilities reference the "nearest" entity. Nearest refers to the entity of the specified kind at a location that can be reached in the fewest number of connections, even if one or more of those conections are blocked by another card ability. The path to the nearest entity is the "shortest" path to that entity.
*** Ownership and Control
    A card's owner is the player whose deck (or game area) held the card at the start of the game.
    A player controls the cards located in his or her out-of-play game area (such as the hand, deck, discard pile).
    The scenario controls the cards in its out-of-play game areas (such as the encounter, act, and agenda deck, and the encounter discard pile).
    - Cards by default enter play under their owner's control. Some abilities may cause cards to change control during a game.
    - If a card would enter an out-of-play area that does not belong to the card's owner, the card is physically placed in the owner's equivalent out-of-play area instead. The card is considered to have entered its controller's out-of-play area, and only the physical placement of the card is adjusted.
*** Parley
    Some abilities are identified with a *Parley* action designator. Such abilities are initiated using the "Active" action (see Activate Action).
*** Per Investigator
    When the Inv symbol appears after a value, that value is multiplied by the number of investigators who started the scenario.
    - The "per investigator" multiplication is done before all other modifiers, and the product of this muliplication is treated as the pnted value of the card.
    - Text that uses the phrase "per investigator" also counts the number of investigators who started the scenario, and is applied before al other modifiers.
    - If investigators have been eliminated from the scenario, they still count toward "per investigator" values.
*** Peril
    Peril is a keyword ability.
    While resolving the drawing of an encounter card with the peril keyword, an investigator cannot confer with the other players. Those players cannot play cards, trigger abilities, or commit cards to that investigator's skill test(s) while the peril encounter is resolving. 
*** Permanent
    Permanent is a deckbuilding keyword ability.
    - A card with the permanent keyword does not count towards your deck size.
    - A card with the permanent keyword still counts as being part of your deck and must therefore adhere to all other deckbuilding restrictions.
    - A card with the permanent keyword starts each game in play and is not shuffled into your investigator deck during setup.
    - A card with the permanent keyword cannot be discarded by any means.
*** Play
    To play a card, an investigator must pay the card's resource cost and meet any applicable play restrictions and conditions. Most cards can only be played by taking a play action (see Play Action).
    A card with the fast keyword is not played during a play action. Such a card may be played any time its specified triggering condition is met or, if it has no triggering condition, during an appropriate player window (see Fast).
    Any time an event card is played, its effects are resolved and it is then placed in its owner's discard pile.
    Any time an asset is played, it is placed in the investigator's play area and remains in play until an ability or game effect causes it to leave play. Most assets take up one or more slots while in play (see Slots).
    Skill cards are not be "played". These cards are /commited/ to a skill test from a player's hand in order to use their abilities.
    See also: Initiation Sequence, Play Restrictions, Permissions, and Instructions.
*** Play Action
    "Play" is an action an invetigator may take during his or her turn in the investigation phase.
    When an investigator takes this action, that investigator selects an asset or event card in his or her hand, pays its resource cost, and plays it (see Play).
    - Cards with the "fast" keyword are not played by using this action (see Fast).
    - Skill cards are not "played". These cards are /commited/ to a skill test from a player's hand in order to use their abilities.
*** Play Restrictions, Permissions, and Instructions
    Many cards and abilities contain specific instructions pertaining to when or how they may or may not be used, or to specific conditions that must be true in order to use them. In order to use such an ability or to play such a card, its play restrictions must be observed.
    A permission allows a player to play a card or use an ability outside the timing specifications provided by the game rules.
    A play instruction describes the timing point at which, and/or time period during which, an event card may be played.
*** Prey
    Given the opportunity, some enemies will pursue a defined investigator. These enemies are identified with the bold word "*prey*" in their text box, followed by instructions on who they should engage.
    - If an enemy that is about to automatically engage an investigator at its locations has multiple options of whom to engage, that enemy engages the investigator who best meets its "prey" instructions (if multiple investigators are tied in meeting these instructions, the lead investigator may decide among them) (see Enemy Engagement).
    - If an enemy that is moving towards the nearest investigator has a choice between multiple equidistant investigators, that enemy must select among those investigators the one who best meets its "prey" instructions. (If multiple equidistant investigators meet the prey criteria, the lead investigator decides among those investigators. see Hunter).
    - If an enemy's prey instructions contain the word "only", that enemy only moves towards and engages that investigator (as if it were the only investigator in play), and ignores all other investigators may use the engage action or card abilities to engage the enemy.
    - Prey has no immediate effect on where an enemy will spawn (see Spawn).
    - Prey has no immediate effect on where an enemy will spawn (see Spawn).
*** Printed
    The word "printed" refers to the text, characteristic, icon, or value that is physically printed on the card.
*** Priority of Simultaneous Resolution
    If an effect affects multiple players simultaneously, but the players must individually make choices to resolve the effect, these choices are made in player order. Once all necessary choices have been made, the effect resolves simultaneously upon all affected entities.
    - If tow or more foreced abilities (including delayed effects) would resolve at the same time, the lead investigator determines the order in which the abilities resolve.
    - If two or more constant abilities and/or lasting effects cannot be applied simultaneously, the lead investigator determines the order in which they are applied.
*** Put into Play
    Some card abilities cause a card to be "put into play". such abilities place the card directly into play from an out-of-play state.
    - The resource cost of a card being put into play *is not paid*.
    - Unless otherwise stated by the put into play ability, cards that enter play in this manner must do so in a play area that satisfies the standard game rules associated with playing or drawing (for encounter cards) that card.
    - A card that has been put into play is not considered to have been played or drawn.
*** Qualifiers
    If card text includes a qualifier followed by multiple terms, the qualifier applies to each term in the list. (/For example, in the phrase "each unique ally and item," the word "unique" is a qualifier that applies both to "ally" and to "item"./)
*** Ready
    A card that is in an upright state so that its controller can read its text from left to right is considered ready.
    - The default state in which cards enter play is ready.
    - When an eshausted card readies, it is returned to the upright state. It is then said to be in a ready state.
    - A ready card cannot ready again (it must first be exhausted, typically by a game step or card ability).
*** Removed from Game
    A card that has been removed from the game is placed away from the game area and has no further interaction with the game in any manner for the duration of its removal.
    If there is no specified duration, a card that has been removed from the game is considered removed until the end of the game.
*** Resign
    Some abilities are identified with a *Resign* action designator. Such abilities are initiated using the "Activate" action (see "Activate Action").
    - When an investigator resings, the investigator is eliminated by resignation (see "Elimination"). An investigator who resigns is not considered to have been defeated.
*** Resource Action
    "Resource" is an action investigator may take during his or her turn in the investigation phase.
    When an investigator takes this action, that investigator gains one resource by taking it form the token pool and adding it to his or her resource pool.
*** Resources
    Resources represent the various means of acquiring new cards at an investigator's disposal - supplies, money, tools, knowledge, spell components, etc.
    - In order to play a card or use an ability that costs resources, an investigator must pay that card or ability's resource cost by taking the specified number of resources from his or her resource pool and returning them to the token pool.
    - Resources can be gained by performing the "Resource" action (see Resource Action).
    - Investigators acquire one resource during each Upkeep phase.
    Also See: "Tokens, Running out of"
*** Retaliate
    Retaliate is a keyword ability.
    Each time an investigator fails a skill test while attacking a ready enemy with the retaliate keyword, after applying all results for that skill test, that enemy performs an attack agains the attacking investigator. An enemy does not exhaust after performing a retaliate attack.
    - This attack occurs whether the enemy is engaged with the attacking investigator or not.
*** Revelation
    A revelation ability may appear on encounter cards or on weakness cards.
    - When an investigator draws an encounter card, that investigator must resolve all "*Revelation*" abilities on the card. This occurs before the card enters play, or in the case of a treachery card, before it is placed in the discard pile.
    - When a weakness card enters an investigator's hand, that investigator must immediately resolve all revelation abilities on the card as if it were just drawn.
*** Sanity and Horror
    Sanity represents a card's mental and emotional fortitude. Horror tracks the harm that has been done to a card's psyche by exposure to the Mythos.
    - When a card takes horror, place a number of horror tokens equal to the amount of horror just taken on the card (see Dealing Damage/Horror)
    - If an investigator has horror on him or her equal to or greater than his or her sanity, that investigator is defeated. When an investigator is defeated, he or she is eliminated from the scenario (see Elimination).
    - In campaign play, an investigator that is defeated by taking horror equal to his or her sanity suffers 1 mental trauma. Taking mental trauma may cause an investigator to be driven *insane*
    - If an asset with a sanity valve has horror on it equal to or greater than its sanity, it is defeated a placed on its owner's discard pile.
    - A card's "remaining sanity" is its base sanity minus the amount of horror on that card, plus or minus any active sanity modifiers.
    - An asset card without a sanity value is not considered to have a sanity of 0, cannot gain sanity, and cannot have horror assigned to it.
    See also: Direct Damage, Direct Horror.
*** Set Aside
    Some scenarios instruct the players to set aside specific cards. Set-aside cards have no interaction with the game until they are referenced by instructions within the scenario or by a card ability.
*** Search
    When a player is instructed to search for a card, that player is permitted to look at all of the cards in the searched area without revealing those cards to the other players.
    - If an effect searches an entire deck, the deck must be shuffled upon completion of the search.
    - When resolving a search effect, a player is obligated to find the object of the search should one more eligible options bo found within the searched area.
    - While cards are in the process of being searched, they are not considered to have left their game area of origin.
*** Self-Referential Text
    When a card's ability text refers to its own title, it is referring to itself only, and not to other copies (by title) of the card.
    Self-referential abilities using the word "this" (e.g. "this card") refer only to the card on which the ability is located, and not to copies of that card.
*** Skill Cards
    Skill cards represent innate or learned attributes or character traits that improve an investigator's skill tests.
    Skill cards are not played from a player's hand. In order to resolve their abilities, skill cards must be /committed/ to a skill test.
    If a skill card is committed to a skill test, its ability may be used during the resolution of that skill test, as specified on the card.
    See Skill Test Timing
*** Skill Tests
    A number of situations in the game require an investigator to make a skill test, using one of his or her four skills: willpower (W), intellect (I), combat (C), or agility (A). A skill test pitsthe investigator's value in a specified skill against a difficulty value that is determined by the ability or game step that initiated the test. The investigator is attempting to match or exceed this difficulty value in order to succeed at the test.
    A skill test is often referred to as a test of the specified skill. (/For example: "agility test", "combat test", "willpower test", or "intellect test"/)
    See Skill Test Timing
*** Slots
    Each investigator has a number of specific slots that can be filled at any given moment. Each asset in an investigator's play area or threat area with a slot symbol is held in a slot of that type. Slots limit the number of asset cards the investigator is permitted to have in play simultaneously.
    The slots normally available to an investigator are:
    - *1 Accessory Slot*
    - *1 Body Slot*
    - *1 Ally Slot*
    - *2 Hand Slots*
    - *2 Arcane Slots*
    If an asset has no slot symbols on it, it does not take up any of the above slots. There is no limit to the number of slot-less assets an investigator can have in play. The symbols to depict which slot an asset fills are printed on the card as: Accessory (necklace), Body (torso), Ally (investigator), 1 Hand (1 hand), 2 Hand (2 hands), 1 Arcane (1 star), 2 Arcane (2 stars).
    If an investigator is at his or her slot limit for a type of asset and wishes to play or gain control of a different asset that would use that slot, the investigator must choose and discard other assets under his or her control simultaneously with new asset entering the slot.
*** Spawn
    Some enemies, when drawn from the encounter deck, spawn in a particular location, indicated by a bold "*spawn*" instruction in the text box.
    - An enemy's spawn instruciton resolves as the enemy enters play, regardless of how it entered play.
    - If an enemy has no spawn instruction, it spawns engaged with the investigator who drew it.
    - If an enemy has no legal locaiton to spawn at (for example, if its spawn instruction directs it to a specific location that is not in play, or if no location in play satisfies its "spawn" instruction), it does not spawn, and is discarded instead.
    - If an enemy's spawn instruction has multiple valid locations, the investigator spawning that enemy decides among those locations.
    - If a card ability instructs the players to spawn an enemy in a particular location (/For example: "Search the encounter deck for an Acolyte and spawn it in Southside"/), treat the ability causing the card to enter play as the enemy's spawn instruction, overriding any other spawn instruction.
*** Standalone Mode
    When playing a standalone game (i.e. playing a single scenario as a one-off adventure, removed from its campaign), the following rules apply:
    - When building a deck for a standalone game, an investigator may use higher level cards in his or her deck (so long as they ovserve the deckbuilding restrictions of the investigator) by counting the total experience of all the higher level cards used in the deck, and taking additional random basic weaknesses based on the following.
      - 0-9 experience: 0 additional random basic weaknesses
      - 10-19 experience: 1 additional random basic weaknesses
      - 20-29 experience: 2 additional random basic weaknesses
      - 30-39 experience: 3 additional random basic weaknesses
      - 40-49 experience: 4 additional random basic weaknesses
      A player cannot include 50 or more experience worth of cards in a standalone deck.
    - After choosing a scenario to play, refer to the Campaign Guide for the campaign that scenario is part of, starting at the setup for that campaign, and continuing on to the first scenario for that campaign. Read through that scenario's introduction, then skip directly to that scenario's resolution and choose a resolution that is amenable to you. You may choose any resolution you wish. (For an added challenge, choose resolutoins that put the investigators in an unfavorable state). If the players are unsure which resolution to choose, or are indifferent, choose *Resolution 1*. Record the results of the chosen resolution in a Campaign Log as if you were playing through in campign mode, *except do not count experience points*.
    - Repeat this process for each scenario up to the scenario you wish to play. Then, setup and play that scenario as normal.
    - If a story decision would occur during gameplay, choose the outcome and record it in your campaign log.
    - Do not apply trauma for having been defeated during gameplay, but if trauma is inflicted during a scenario resoluiton, apply it.
    - if a scenario weakness or asset is earned that is in an expansion you do not own, simply continue without that card.
*** Surge
    Surge is a keyword ability.
    After drawing and resolving an encounter with the surge keyword, an investigator must draw another card from the encounter deck.
    - If a card with the surge keyword is drawn during setup, the surge keyword does resolve.
*** Taking Damage/Horror
    "Take X damage" is shorthand for "deal X damage to your investigator". "Take X horror" is shorthand for "deal X horror to your investigator".
    See Dealing Damage/Horror
*** Target
    The term "choose" indicates that one or more targets must be chosen in order for an ability to resolve. The player resolving the ability must choose a game element (usually a card) that meets the targeting requirements of the ability.
    - If an ability requires the choosing of a target, and there is no valid target (or not enough valid targets), the avility cannot be initiated.
    - If multiple targets are required to be chosen by the same player, they are chosen simultaneously.
    - An effect that can choose "any number" of targets does not successfully resolve (and cannot change the game state) if zero of those targets are chosen.
    - A card is not eligible target for an ability if the resolution of that ability's effect could not change the target's state. (/For example, an exhausted enemy could not be chosen as the target of an effect that reads, "choose and exhaust an enemy."/)
*** Then
    If the effect of an ability includes the word "then", the text preceding the word "then" must be successfully resolved in full before the remainder of the effect described after the word "then" can be resolved.
    - If the pre-then aspect of an effect does successfully resolve in full, the post-then aspect of the effect must also resolve.
    - The post-then aspect of an effect has timing priority over all other indirect consequences of the resolution of the pre-then aspect. (/For example, if an effect reads: "Draw an encounter card. Then, take 1 horror", and a player controls an ability that reads "After you draw an encounter card", the post-then "take 1 horror" aspect occurs before the "After you draw an encounter card" ability may initiate./)
    - If the pre-then aspect of an effect does not successfully resolve in full, the post-then aspect does not resolve.
*** Threat Area
    An investigator's threat area is a play area in which encounter cards currently engaged with and/or affecting an investigator are placed.
    - The cards in an investigator's threat area are at the same location as the investigator.
*** Tokens, Running out of
    There is no limit to the number of tokens (of any type) which can be in the game area at a given time. If players run out of the provided tokens, other tokens, counters, or coins may be used to track the current game state.
*** Traits
    Most cards have one or more traits listed at the top of the text box and printed in bold italics.
    - Traits have no inherent effect on the game. Instead, some card abilities reference cards that possess specific traits.
*** Trauma
    See Campaign Play
*** Treachery Cards
    Treachery cards represent curses, afflictions, madnesses, obstacles, disasters, or other unexpected occurrences an investigator may encounter throughout the course of a scenario.
    When a treachery card is drawn by an investigator, that investigator must resolve its effects. Then, place the card in its discard pile unless otherwise instructed by the ability.
*** Triggered Abilities
    A triggered ability is an ability that is optionally triggered by a player. A triggered ability can be identified by one of the following icons. 
    - The ATA icon indicates an action-costed triggered ability.
    - the FTA icon indicates a free triggered ability that does not cost an action and may be used during any player window.
    - The RTA icon indicates a reaction triggered ability that does not cost an action and may be used any time its triggering condition is met.
    See also: Ability, Initiation Sequence
*** Triggering Condition
    A tiggering condition indicates the timing point at which an ability may be triggered. Most triggering conditions use the word "when" or "after" to establish their relation to the specified timing point.
    - Each eligible ability that triggers in reference to a specified timing point may be used once each time that timing point occurs.
    - If multiple instances of the same ability are eligible to initiate, each instance may be used once.
    See also: Ability, After, When
*** Unique (\*)
    A card with the \* symbol before its card title is a unique card. There can be no more than one instance of each unique card, by title, in play at any given time.
    - A player cannot bring into play a unique card if a copy of that card (by title) is already in play.
    - If a unique encounter card that shares a title with a unique player card that would enter play, discard the player card simultaneously as the encounter card enters play.
*** Upkeep Phase
    See Upkeep Phase
*** Uses (X "type")
    Uses is a keyword ability.
    When a card bearing this keyword enters play, place a number of resource token equal to the value (X), from the token pool, on the card. The word following the value establishes and identifies the type of uses this card bears. The resource tokens placed on the card are considered uses of the established type, and are not considered resource tokens.
    - Each card bearing this keyword also has an ability which references the type of use established by the keyword as a part of its cost. When such an ability spends a use, a token or that type must be removed from the card bearing the ability.
    - Other cards may reference and interact with uses of a specified type, usually by adding uses of that type to a card, or using uses of that type for other purposes.
    - A card cannot bear uses of a type other than that established by its own "Uses (X type)" keyword. (/For example, a card with  "Uses (4 ammo)" cannot gain charges/)
    - Some cards with this keyword vear text that cause the card to be discarded if it has no uses remaining. If the card contains no such text, it remains in play even if out of uses.
*** Vicorty Display, Victory Points
    Some encounter cards are worth victory points. The text *Victory X* indicates that a card is worth X victory points.
    An encounter card worth victory points that is overcome by the investigators is soted in the victory display until the end of the scenario. The victory display is an out-of-play game area shared by all players. Upon completion of the scenario, the cards in the victory display provide experience, which can be used to upgrade an investigator's deck (see Campaign Play).
    - As a victory point enemy is defeated, place the card in the victory display instead of in the discard pile.
    - At the end of a scenario, place each victory point location that is in play, revealed, and with no clues on it in the victory display.
    - As a victory point treachery card completes its resolution, place it in the victory display instead of in the discard pile.
*** Weakness
    Weakness is a card sub-type. These cards represent character flaws, curses, madnesses, injuries, tasks, enemies, or story elements that are part of an investigator's backstory, or that are acquired over the course of a campaign. Weakness cards are resolved differently depending upon their cardtype.
    - When an investigator draws a weakness with an encounter cardtype (/for example, an enemy or a treachery weakness/), resolve that card as if it were just drawn from the encounter deck.
    - When an investigator draws a weakness with a player cardtype (/for example, an asset, an event, or a skill weakness/), resolve any Revelation effects on the card, and add it to that investigator's hand. The card may then be used as any other player card of its type.
    - If a weakness enters an investigator's hand in a manner that did not involve drawing the card, that investigator must resolve the card (including any Revelation abilities) as if he or she had just drawn it.
    - The bearer of a weakness is the investigator who started the game with the weakness in his or her deck or play area.
    - If a weakness is added to a player's deck or hand during the play of a scenario, that weakness remains part of that investigator's deck for the rest of the campaign. (Unless it is removed from the campaign by a card ability or scenario resolution)
    - A player may not optionally choose to discard a weakness car from hand, unless a card explicity specifies otherwise.
    - Weaknesses with an encounter cardtype are, like other encounter cards, not controlled by any player. Weaknesses with a player cardtype are controlled by their bearer.
    - Some card and game text references a "basic weakness." A basic weakness can be identified by the presence of the words "Basic Weakness" and the symbol.
*** When
    The word "when" refers to the moment immediately after the specified timing point or triggering condition initiates, but before its impact upon the game state resolves. The resolution of a "when" ability interrupts the resolution of its timing point or triggering condition. (/For example, an ability that reads "When you draw an enemy card" initiates immediately after you draw the enemy card, but before resolving its revelation ability, spawning it, etc./)
    See also: Ability, Priority of Simultaneous Resolution
*** Winning and Losing
    Eacn scenario has a number of different possible endings.
    The act deck represents the progress of the investigators through a scenario. Some instructions in the act deck (as well as on other encounter card types) contain resolution points, in the format of : "(-> *R#*)". The players' primary objective is to advance through the act deck until a (hopefully favorable) resolution point is reached. Shoudl the act deck invoke a resolution, the players have completed the scenario (they may have even "won!"). Instructions for resolving the designated resolution are found in the "do not read until end of game" section of the campaign manual.
    The agenda deck represents the objectives and progress of the malicious forces pitted against the investigators in the scenario. Some instructions in the agenda deck (as well as on other encounter cardtypes) also contain resolution points, in the format of: "(-> *#R*)". Should the agenda deck invoke a (usually darker) resolution, the players have lost the scenario. Instructions for resolving the designated resolution are found in the "do not read until end of game" section of the campaign guide.
    Should the scenario end with no resolution being reached (/for example, if all investigators have been eliminated or have resigned/), instructions for resolving the scenario can be found in the "do not read until end of game" section of the campaign guide.
    - If playing in a campaign, players will proceed to the next scenario in the campaign regardless of the outcome of the scenario. Even if players "lose" a scenario, they still continue their campaign (although with some negativ consequences from their failure).
    - When playing a standalone scenario, players either win or lose the scenario. They win if they complete a resolution on an act card. Any other esolution is considered a loss (see Standalone Mode)
    See Act Deck and Agenda Deck
*** The letter 'X'
    The value of the letter X is defined by a card ability or a granted player choice. If X is not defined, its value is equal to 0.
    - For costs involving the letter X, the value of X is defined by card ability or player choice, after which the amount paid may be modified by effects without altering the value of X.
*** You/Your
    - An ability on a card in play referencing "you" or "your" refers to the investigator who controls, is engaged with, or is currently interacting with the card.
    - A Revelation ability that references "you" or "your" refers to the investigator who drew the card and is resolving the ability.
    - While resolving an ability initiated by the active action, "you" or "your" refers to the investigator performing the action.
** Appendix 1: Initiation Sequence
   When a player wishes to initiate a triggered ability or play a card, that player first declares his or her intent. There are two preliminary confirmations that must be made before the process of initiating an ability or playing a card may begin. These are:

   - Check play restrictions: determine if the card can be played, or if the ability can be initiated, at this time. (This includes verifying that the resolution of the effect has the potential to change the game state.) If the play restrictions are not met, abort this process.
   - Determine the cost (or costs, if multiple costs are required) to play the card or initiate the ability. If it is established that the cost (taking modifiers into account) can be paid, proceed with the remaining steps of this sequence.

   Once each of the above confirmations has been made, follow these steps, in order: 

   1. Apply any modifiers to the cost(s).
   2. Pay the cost(s). If this step is reached and the cost(s) cannot be paid, abort this process without paying any costs.
      - Upon completion of this step, attacks of opportunity, if applicable, resolve.
   3. The card commences being played, or the effects of the ability attempt to initiate.
   4. The effects of the ability (if not canceled in step 3) complete their initiation, and resolve. The card is regarded as played ( and placed in play, or in its owner's discard pile if it's an event), and the ability is considered resolved simultaneously with the completion of this step.
      - If the ability being initiated is on an in-play card, the sequence does not stop from completing if that card leaves play during the sequence.
** Appendix 2: Timing and Gameplay
   The "Phase Sequence timing chart" depicts the phases and steps of a game round. Each time an investigator makes a skill test, use the skill test timing detailed in the "Skill Test timing chart."

   Numbered items presented in the grey boxes are known as framework events. Framework events are mandatory occurrences dictated by the structure of the game. 

   The red boxes are player windows. Players may use triggered abilities in these windows.
*** Framework Event Details

*** Skill Test Timing
** Appendix 3: Set Up the Game
** Appendix 4: Card Anatomy

* Investigator Additional Rules
** Customizable
   Customizable is a keyword that appears on some player cards in this expansion. Customizable cards might seem unremarkable at first, but have tremendous potential for improvement over the course of a campaign. By spending experience points, each one can be custom-tailored to become a powerful tool in an investigator's deck.
   Each customizable card starts at level 0 and has a separate sheet containing a checklist of upgrades that can be perchased using experience points. Each upgrade is accompanied by one or more checkboxes.
   Unless otherwise specified by a card effect, an investigator can only mark checkboxes on an upgrade sheet before or after a scenario, when they are upgrading their deck or purchasing new cards for their deck. Spending 1 point of experience allows an invstigator to mark one checkbox on one of their card's upgrade sheets.
   To purchase an upgrade, an investigator must mark all of an upgrade's checkboxes. Once an upgrade is purchased, /each copy/ of the card it is paired with is treated as having that upgrade (as a gained card ability) for that investigator only.
   - A customizalbe card's level is equal to have the total number of checkboxes marked on its upgrade sheet, rounded up.
     - /Note that this emans some investigators are not able to upgrade a customizable card past a certain point, if their deckbuilding options would forbid them from including the card in their deck after the upgrade is made/
   - An upgrade sheet cannot have more than a total of 10 checkboxes marked.
   - Spending experience points on one or more upgrades for a customizable card already in an invstigator's deck is considered to be "upgrading" a card for the puposes of card effects.
   - An investigator may directly purchase one or more copies of a customizable card with one or more upgrades by spending /only/ the amount of experience points required to purchase those upgrades. /(Doing so counts as purchasing a new card, not upgrading an existing card.)/
   - Upgrades for customizable cards are considered to be present on a card at all times (even while the card is in an out-of-play area, such as an investigator's hand or discard pile).
   - Spending 1 or more experience points on upgrades on a customizable card's upgrade hseet is permanent and cannot be refunded.
   - During gameplay, upgrade sheets should be placed in an out-of-play area nearby, so they can be quickly referenced.
** Dilemmas and Revelation Abilities
   Some player cards in this expansion (namely those with the *Dilemma* trait) possess revelation abilities. As with revelation abilities on other cardtypes, these abilities resolve when the card is drawn or otherwise enters your hand, not when the card is played.
   - These cards have not cost ("-"). These cards cannot be played; their effects only resolve when they are drawn or added to your hand.
   - After resolving a revelation ability on a player card, place it in its owner's discard pile.
   - Revelation abilities do not resolve during setup. If one or more player cards with revelation abilities are drawn during setup, wait until the game begins, then each player (in player order) resolves all of their own revelation abilities in the order of their choosing.
** "Exile"
   Some player cards must be exiled when they are used. When a card is exiled, it is removed from the game and returned to the collection. During campaign play, a card that has been exiled must be purchased again with experience points (between scenarios) before an investigator can re-include it in their deck. If exiling one or more cards would reduce an investigator's deck below their deck size, when purchasing cards between scenarios, they must purchase cards so that a legal deck size is maintained (when purchasing cards in this manner, they may purchase level-0 cards for 0 experience cost until a legal deck size is reached).
** Lola and "Roles"
   As a renowned actrss, Lola Hayes can play many different roles. At the beginning of each scenario, after investigators draw opening hands, Lola Hayes must choose a role (Neutral, Guardian, Seeker, Rogue, Mystic, or Survivor). Lola can only play cards, commit cards to skill tests, or trigger ATA, FTA, or RTA abilities on Neutral cards or cards whose class matches her role. This restriction only applies to player cards, not to encounter cards or weaknesses. Notes that Constant and *Forced* abilities remain active on cards whose class does not match Lola's role.
** Researched
   Researched is a keyword ability that appears on some higher-level cards (most prominently on Seeker cards).
   To be included in an investigator's deck, a card with the Researched keyword must first be "identified" or "translated" by performing a task on the lower-level version of that card and recording the result in your Campaign Log.
   - An investigator can only include a researched card in their deck by upgrading it from its lower-level version.
   - An investigator can only include a researched card in their deck if, in their Campaign Log, they have recorded the completion of the task described in the lower-level version of that card.
   - After an investigator has completed this task and recorded it in the Campaign Log, any investigator in that campaign may upgrade that relevant card following the normal rules for upgrading player cards.
* Carnevale of Horrors
** Expansion
   - /Carnevale of Horrors/
/Carnevale of Horrors/ can be played in one of two ways: As a standalone scenario, or as a side-story inserted into any campaign.
** Standalone Mode
   When played as a standalone scenario, follow the steps for Standalone Mode in the Rules Reference. There is no campaign guide for /Carnevale of Horrors/; instead refer to this card for additional setup instructions.
   When played as a standalone scenario, /Carnevale of Horrors/ has only two difficulty modes. Construct the chaos bag with the following tokens:
   - Standard: +1, 0, 0, 0, -1, -1, -1, -2, -3, -4, -6, S, S, S, C, T, O, F, E
   - Hard: +1, 0, 0, 0, -1, -1, -3, -4, -5, -6, -7, S, S, S, C, T, O, F, E
** Side-Story (Campaign Mode)
   A side-story is a scenario that may be played between any two scenarios of an /Arkham Horror: The Card Game/ campaign. Playing a side-story costs each investigator in the campaign with a certain amount of experience. Weaknesses, trauma, experience, and rewards granted by playing a side-story stay with the investigators for the remainder of the campaign. Each side-story may only be played once per campaign.
   When played as a side-story during a campaign, play this scenario as if you are setting up the next scenario in the campaign, with the same chaos bag, weaknesses, trauma, and story assets previously earned.
   *Playing the /Canrevale of Horrors/ side-story costs each investigator 3 experience.*
** Setup
   - Gather all cards from the /Carnevale of Horrors/ encounter set, indicated by this icon.
   - Choose 1 location at random and remove it from the game. If San Marco Basilica or Canal-side is chosen, randomly choose a different location instead.
   - Put the other 8 locations into play, in a random circular formation. Each investigator begins play at San Marco Basilica. Put Abbess Allegria Di Biase into play at San Marco Basilica.
   - Shuffle the 7 Masked Carnevale-Goers and put 1 into play at each location other than San Marco Basilica, Masked Carnevale-Goer side face-up. Do not look at their other sides.
   - Set the following cards aside, out of play: Cnidathqua, Pantalone, Medico Della Peste, Bauta, Gilded Volto.
   - Shuffle the remainder of the encounter cards to build the encounter deck.
** Additional Clarifications
*** Location Setup
In this scenario, locations are placed in a circle. Due to the parade during the Carnevale, each location is connected only to the location in the clockwise direction. This means that investigators and monsters can only travel (or count the nearest location) in the clockwise direction unless otherwise directed.
*** Counter-Clockwise
Some cards instruct the players to find the nearest location in the counter-clockwise direction. This is an exception to the above rule and should be followed as though locations are connected counter-clockwise.
*** "Across From"
The location "across from" another location is the farthest location, equidistant in both the clockwise and counter-clockwise directions. For the purposes of this scenario, "across from your location" and "across from you" have the same meaning.
* Curse of the Rougarou
** Expansion
   - /Curse of the Rougarou/
/Curse of the Rougarou/ can be played in one of two ways: As a standalone scenario, or as a side-story inserted into any campaign.
** Standalone Mode
   When played as a standalone scenario, follow the steps for Standalone Mode as defined in the rules reference. There is no campaign guide for /Curse of the Rougarou/; instead refer to the section below for additional setup instructions. 
   When played as a standalone scenario, /Curse of the Rougarou/ has only two difficulty modes. Construct the chaos bag with the following tokens:
   - Standard: +1, +1, 0, 0, 0, -1, -1, -1, -2, -2, -3, -3, -4, -4, -5, -6, S, S, C, C, T, O, F, E
   - Hard: +1, 0, 0, 0, -1, -1, -1, -2, -2, -3, -3, -4, -4, -5, -5, -6, -8, S, S, S, C, C, T, O, F, E
** Side-story (Campaign Mode)
   A side-story is a scenario that may be played between any two scenarios of an Arkham Horror: The Card Game campaign. Playing a side-story costs each investigator in the campaing a certain amount of experience. Weakness, trauma, experience, and rewards granted by playing a side-story stay with the investigators for the remainder of the campaign. Each side-story may only be played once per campaign.
   When played as a side-story during a campaign, play this scenario as if you are setting up the next scenario in the campaign, with the same chaos bag, weakness, trauma, and story assets previously earned.
   *Playing the /Curse of the Rougarou/ side-story costs each investigator 1 experience.*
** Setup
   - Gather all cards from the following encounter sets: /Curse of the Rougarou/ and /The Bayou/.
   - Set the /Curse of the Rougarou/ encounter set aside, out of play. 
   - Sort each location into 4 piles, by trait (/*New Orleans*/, /*Riverside*/, /*Wilderness*/, and /*Unhallowed*/). Randomly choose 1 of these piles and remove those locations from the game. Randomly choose another 1 of these piles and put those locations into play. Set each location in the other 2 piles aside, out of play. Each investigator begins play at the /*Bayou*/ location in play.
   - Set the following cards aside, out of play: Lady Esprit, Bear Trap, and Fishing Net.
   - Shuffle the remainder of the encounter cards to build the encounter deck.
* Machinations Through Time
** Expansion
   -/Machinations Through Time/
   /Machinations Through Time/ can be played as either a standalone scenario or as a side-story inserted into any campaign. When played standalone, it can be played in one of two ways: with a single group of 1-4 players in /Single Group Mode/, or with 3-12 players split into three groups of 1-4 players each in /Epic Multiplayer Mode/.
   Included are additional rules and clarifications for both versions of the scenario and special rules pertaining to /Epic Multiplayer Mode/.
** Standalone Mode
   When played as a standalone scenario, follow the steps for Standalone Mode in the Rules Reference. This section is the campaign guide for /Machinations Through Time/. This scenario has four difficulty modes. Each group may play on its own difficulty mode. Construct the chaos bag with the following tokens.
   - Easy: +1, +1, +1, 0, 0, 0, 0, -1, -1, -1, -2, -2, S, C, T, O, F, E
   - Standard: +1, 0, 0, -1, -1, -1, -2, -2, -3, -4, S, S, C, T, O, F, E
   - Hard: 0, 0, -1, -1, -1, -2, -3, -4, -6, S, S, C, T, O, O, F, E
   - Expert: 0, -1, -1, -2, -3, -4, -5, -6, -8, S, S, C, T, O, O, F, E
** Side-Story (Campaign Mode)
   A side-story is a scenario that may be played between any two scenarios of an Arkham Horror: LCG campaign. Playing a side-story costs each investigator in the campaign a certain amount of experience. Weakness, trauma, experience, and rewards granted by playing a side-story stay with the investigator sfor the remainder of the campaign. Each side-story may only be played once per campaign.
   When this scenario is played as a side-story during a campaign, play it as if you are setting up the next scenario in the campaign, with the same chaos bag, weakness, trauma, and story assets perviously earned.
   *Playing the /Machinations Through Time/ side-story costs each investigator 2 experience.*
** Aditional Rules & Clarifications
*** Eras
    /Machinations Through Time/ has three separate eras: past, present, and future. In /Single Group Mode/, you play all three eras simultaneously and may travel through all eras. In /Epic Multiplayer Mode/, each group is confines to a separate era.
    - A /*Past*/ asset cannot enter a non-/*Past*/ location.
    - A /*Present*/ asset cannot enter a non-/*Present*/ location.
    - A /*Future*/ non-/*Item*/ asset cannot enter a non-/*Future*/ location.
*** Time Paradox
    During /Machinations Through Time/, you may be confronted with seemingly impossible tasks. Some tasks require the help of investigators in another era to complete. Communication is key.
*** Story Cards
    Story cards are a cardtype in this scenario. These cards serve as an avenue for additional narrative and game text. During setup, resolve the *Setup* text on each story card in play. Abilities on story cards in play can be triggered by any investigator.
*** Announce
    When a card instructs you to "announce" a key phrase, if you are playing in /Epic Multiplayer Mode/, clearly communicate that phrase to the other two groups. Some abilities require an announcement to have been made before they can be triggered. See Announcements section for a list of all announcements.
*** Abducted and Rescued
    When a /*Scientist*/ asset is abducted (via card or game text), remove all counters from it and set it aside, out of play. It remains out of play until it is rescued (via card or game text).
*** Alert
    Each time an investigator fails a skill test while attempting to evade an enemy with the alert keyword, after applying all results for that skill test, that enemy performs an attack against the evading investigator. An enemy does not exhaust after performing an alert attack. This attack occurs whether the enemy is engaged with the evading investigator or not.
*** Patrol
    Some enemies have the patrol keyword. During the enemy phase (in frameword step 3.2), each ready, unengaged enemy with the patrol keyword moves to a connecting location along the shortest path towards the designated location (as described in parentheses next to the word patrol).
    - If there are multiple locations that qualify as the designated location, the elad investigator may choose which location the enemy moves towards.
    - If an enemy with patrol would be compelled to move to a location that is blocked by a card ability, the enemy does not move.
*** Global Values
    Global values are calculated based on the total number of participating players among all groups at the start of the game.
    - Any values 'X' that are calculated on a per investigator basis, it is all investigators in all eras for the global value.
** Epic Multiplayer Modes
   To play /Machinations Through Time/ in /Epic Multiplayer Mode/, first divide the investigators into three separate groups - Past Group, Present Group, and Future Group. At least one investigator must be assigned to each group, and no more than four investigators may be assigned to a single group. While it is possible to play with groups of differently numbered players, split players between groups as evenly as possible. Each group requires one copy of /Machinations Through Time/ in order to play. During gameplay, observe the following additional rules:
    - Each group has its own play area, and plays the game separately from the other groups. Rules, actions, and card effects cannot affect investigators in other groups, unless explicitly stated otherwise.
    - Each group can proceed to the next round or agenda independently of one another; there is no need to wait until all groups have reached the same point before proceeding.
    - Investigators may freely communicate between groups.
*** Time Limit
    When playing in /Epic Multiplayer Mode/, the players (or your event organizer) may impose a time restriction for the game. the default time limit is *180 minutes*. The players (or your event organizer) may impose a different time restriction, often depending on the number of players. When this time limit has passed, any groups that are still playing must immediately advance to agenda 2b.
** Setup for Single Group Mode
    - Gather all cards from the /Machinations Through Time/ and /Single Group Mode/ encounter sets. These sets are indicated by their respective icons.
    - Set the Corrigan Industries location aside, out of play. Put the Tindalos location into play, using the side with the /Single Group Mode/ encounter set icon. Put the remaining fourteen locations into play (/see the locaiton placements in location section, ignoring the placement for Tindalos/).
    - Each investigator begins play at Tindalos.
    - Put the A Noble Legacy (Past), A Noble Legacy (Present), A Noble Legacy (Future) story cards into play, one at a time, and resolve the *Setup* text on each of them. (/Hint - When playing, first focus on completing A Noble Legacy (Past), then focus on A Noble Legacy (Present), and, lastly, A Noble Legacy (Future)./)
    - Choose one of the three /*Machination*/ story cards at random, put it into play, and resolve its *Setup* text. Remove the other two /*Machination*/ story cards from the game.
    - Choose one of the three /*Plot*/ story cards at random, put it into play, and resolve its *Setup* text. Remove the other two /*Plot*/ story cards from the game.
    - Add (1 * Inv) doom to agenda 1a. Then if you are not playing on Standard difficulty, check the difficulty level:
      - If it is Easy difficulty, remove 1 doom from agenda 1a.
      - If it is Hard difficulty, add 1 doom to agenda 1a.
      - If it is Expert difficulty, add 2 doom to agenda 1a.
    - Shuffle the remaining 33 encounter cards to form the encounter deck.
    - Ready to Begin
** Setup for Epic Multiplayer Mode
    - Gather all cards from the /Machinations Through Time/ and /Epic Multiplayer Mode/ encounter sets. These sets are indicated by their respective icons.
    - Depending on which group you are in (Past Group, Present Group, or Future Group), follow the setup instructions for that group.
*** Setup for Past Group
    - Put the Tindalos location into play, using the side with the /Epic Multiplayer Mode/ encounter set icon. Put the five /*Past*/ locations into play (/see location placement/) Remove the remaining locations from the game.
      - Each investigator begins play at Tindalos
    - The the A Noble Legacy (Past) story card into play and resolve its *Setup* text. Remove the other two A Noble Legacy story cards from the game. 
    - Remove all /*Present*/ and /*Future*/ story assets from the game.
    - Choose one of the three /*Machination*/ story cards at random, announce its title, put it into play, and resolve its *Setup* text. Remove the other two /*Machination*/ story cards from the game.
    - Choose one of the three /*Plot*/ story cards at random, announce its title, put it into play, and resolve its *Setup* text. Temove the other two /*Plot*/ story cards from the game.
    - Add (1 * Inv) doom to agenda 1a. Then if you are not playing on Standard difficulty, check the difficulty level:
      - If it is Easy difficulty, remove 1 doom from agenda 1a.
      - If it is Hard difficulty, add 1 doom to agenda 1a.
      - If it is Expert difficulty, add 2 doom to agenda 1a.
    - Shuffle the remaining 33 encounter cards to form the encounter deck.
    - Ready to Begin
*** Setup for Present Group
    - Put the Tindalos location into play, using the side with /Epic Multiplayer Mode/ encounter set icon. Put the five /*Present*/ locaitons into play (/see location placement/). Remove the remaining locations from the game.
      - Each investigator begins play at Tindalos.
    - Put the A Noble Legacy (Present) story card into play and resolve its *Setup* text. Remove the other two A Noble Legacy story cards from the game.
    - Remove all /*Past*/ and /*Future*/ story assets from the game.
    - Put the announced /*Machination*/ story card into play and resovle its *Setup* text. Remove the other two /*Machination*/ story cards from the game.
    - Put the announced /*Plot*/ story card into play and resolve its *Setup* text. Remove the other two /*Plot*/ story cards from the game.
    - Add (1 * Inv) doom to agenda 1a. Then if you are not playing on Standard difficulty, check the difficulty level:
      - If it is Easy difficulty, remove 1 doom from agenda 1a.
      - If it is Hard difficulty, add 1 doom to agenda 1a.
      - If it is Expert difficulty, add 2 doom to agenda 1a.
    - Shuffle the remaining 33 encounter cards to form the encounter deck.
    - Ready to Begin
*** Setup for Future Group
    - Put the Tindalos locaiton into play, using the side with the /Epic Multiplayer Mode/ encounter set icon. Set the Corrigan Industries location aside, out of play. Put the four /*Future*/ locations into play (/see location placement/). Remove the remaining locations from the game.
      - Each investigator begins play at Tindalos.
    - Put the A Noble Legacy (Future) story card into play and resolve its *Setup* text. Remove the other two A Noble Legcy story cards from the game.
    - Remove all /*Past*/ and /*Present*/ story assets from the game.
    - Put the announced /*Machination*/ story card into play and resolve its *Setup* text. Remove the other two /*Machination*/ story cards from the game.
    - Put the announced /*Plot*/ story card into play and resolve its *Setup* text. Remove the other two /*Plot*/ story cards from the game.
    - Add (1 * Inv) doom to agenda 1a. Then if you are not playing on Standard difficulty, check the difficulty level:
      - If it is Easy difficulty, remove 1 doom from agenda 1a.
      - If it is Hard difficulty, add 1 doom to agenda 1a.
      - If it is Expert difficulty, add 2 doom to agenda 1a.
    - Shuffle the remaining 33 encounter cards to form the encounter deck.
    - Ready to Begin
** Location Placement
*** Location Placement for the Past
|            | Arkham Gazette        |                      |
|------------+-----------------------+----------------------|
|River Docks | Tindalos              | O'Malley's Watch Shop|
|------------+-----------------------+----------------------|
|            | Miskatonic University |                      |
|------------+-----------------------+----------------------|
|            | Childhood Home        |                      |

*** Location Placement for the Present
|             | Arkham Adviser        |                |
|-------------+-----------------------+----------------|
| River Docks | Tindalos              | Tick-Tock Club |
|-------------+-----------------------+----------------|
|             | Miskatonic University |                |
|-------------+-----------------------+----------------|
|             | Ye Olde Magick Shoppe |                |

*** Location Placement for the Future
|             | Arkham Adviser        |                |
|-------------+-----------------------+----------------|
| River Docks | Tindalos              | Tick-Tock Club |
|-------------+-----------------------+----------------|
|             | Miskatonic University |                |

** Optional Variants
   For a more challenging and thematic experience, try playing with any number of the following variants:
   - When a /*Past*/ version of the Thomas Corrigan or Mayr Zielinski asset is abducted, announce that their /*Present*/ version (in the present era) is also abducted. When a /*Present*/ version of the Thomas Corrigan or Mary Zielinski asset is abducted, announce that their /*Future*/ version (in the future era) is also abducted.
   - During setup, instead of choosing one /*Plot*/ story card, choose two /*Plot*/ story cards at random, put them into play, one at a time, and resolve the *Setup* text on each of them (/instead of removing enemies from the game, set them aside/). Remove the other /*Plot*/ story card from the game. For an extra challenging experience, put all three /*Plot*/ story cards into play!
*** Single Group Mode
   - When two or more /*Scientist*/ assets with the same title are in play at Tindalos, they all faint from seeing one another. Deal 5 horror to each of those assets.
*** Epic Multiplayer Mode
   - Instead of playing independently of one another, at the end of each round, each group must pause the game and wait until all three groups have reached the end of the round before proceeding to the next round.
** Announcements
   The following is a list of announcements that can be made as the investigators play the /Machinations Through Time/ scenario. As the investigators complete each of these announcements, check the box next to them. 
- [ ] "Thomas and Mary have met."
- [ ] "Thomas and Mary have been inspired by Nikola Tesla."
- [ ] "Funding for an observatory has begun."
- [ ] "The observatory is built."
- [ ] "Teleportation research has begun."
- [ ] "Corrigan Industries has been founded."
- [ ] "Thomas and Mary have made a historic discovery."
- [ ] "Thomas and Mary have won a Nobel Prize."
- [ ] "A tree seed has been planted."
- [ ] "Thomas and Mary have married."
- [ ] "The debt has been paid."
